/**
 * Data Module
 * Contiene todos los datos estáticos de la aplicación
 */

const protocolRules = [
    { number: "1", title: "Presentación Inicial", content: `ONLINE: "Hola, hablas con Martina de Clínica Cialo. Estaré encantada de ayudarte y resolver tus dudas 😊"\nPRESENCIAL: Buenos días/buenas tardes, bienvenido/a a Clinica Cialo. ¿En qué te podemos ayudar?` },
    { number: "2", title: "Nunca dejar en visto", content: `Todos los mensajes se responden. Si no sabes, avisa: "Estoy revisando la información para entregártela enseguida 🙌"\nNUNCA culpar a un paciente, siempre velar por darle solución.` },
    { number: "3", title: "Tiempo de Respuesta", content: `Máximo 10 min. Si hay carga: "Disculpe la demora en responder, son demasiados los mensajes que nos llegan 😩. Ya te ayudo con tu consulta."` },
    { number: "4", title: "Cierre de Respuesta", content: `Todas las respuestas de tratamientos deben finalizar con: "¿Deseas que agendemos tu cita?"\nEn general, terminar con pregunta para mantener activo: "¿Quieres que te enviemos la disponibilidad?" / "¿Prefieres que te mande fotos de resultados?"` },
    { number: "5", title: "Escalamiento", content: `Si no sabes, consulta a Natacha, Pablo o Nicolás. NUNCA INVENTAR ni dar información poco clara.` },
    { number: "6", title: "Manejo de Precios", content: `Si no conoces un valor exacto: "Para confirmarte el valor exacto, voy a consultar de inmediato con el equipo. Te escribo en un momento 🙌"` },
    { number: "7", title: "Estilo Comunicación", content: `Amable, cercano y profesional. Siempre con emojis moderados que transmitan calidez, pero sin abuso. Evitar mensajes secos de una palabra.` },
    { number: "8", title: "Principios Clave", content: `Disponibilidad total: que el paciente siempre sienta que es prioridad.\nEmpatía activa: "Te entiendo perfectamente", "Es una excelente pregunta", "Nos pasa mucho en estos casos".\nLenguaje positivo: nunca "no se puede"; cambiar por "Lo verifico de inmediato" o "Busquemos la mejor opción para ti".` },
    { number: "9", title: "Ambiente Sala Espera", content: `Música moderada. PROHIBIDO género urbano/reguetón. Reportar suciedad a Aseo inmediatamente para mantener la clínica impecable.` },
    { number: "10", title: "Área de Mesón", content: `Mantener siempre ordenado, con mínima cantidad de objetos en superficie. PROHIBIDO comer ("picotear") frente a pacientes. No puede quedar ningún residuo a la vista.` },
    { number: "11", title: "Uso Computador", content: `Volumen activo para escuchar alertas de Reservo. Especial atención a cambios de valores de pago.` },
    { number: "12", title: "Pacientes Tratamientos Láser", content: `Consultar proactivamente si desea productos post-láser:\n• Agua termal (calmar y refrescar)\n• Cicalfate (regeneración cutánea)\nPregunta directa: "¿Quieres que te llevemos agua termal o Cicalfate para tu recuperación post láser?"\nLas cremas pueden cambiar según stock.` },
    { number: "13", title: "Aviso Suspensión Dr.", content: `Si un paciente cancela a última hora y el profesional tiene agenda reducida ese día, AVISAR DE INMEDIATO. Permite reorganizar jornada y evitar tiempos muertos. Nunca omitir esta comunicación.` },
    { number: "14", title: "Suspensión Paciente", content: `Si cancela con tiempo, preguntar CUÁNDO reagenda (dar por hecho la continuidad). Nunca preguntar "si desea reagendar".\nEjemplo: "¿Qué día y horario te acomoda para reagendar tu cita?" / "Tenemos disponibilidad el día ___ a las ___ horas, ¿te acomoda?"` },
    { number: "15", title: "Oferta de Horarios", content: `Dar opciones cerradas, evitando preguntas abiertas. Dar por hecho que el paciente ya está concretando.\nCorrecto: "¿Le acomoda jueves o viernes?" / "¿Prefiere en horario de mañana o al mediodía?"\nIncorrecto: "¿Le gustaría agendar una hora?"` },
    { number: "16", title: "Evaluaciones Dr. Nicolás Laucirica", content: `EVALUACIONES GRATUITAS:\n📅 Días: Lunes, Martes, Jueves y Viernes\n🕐 Horarios: 9:00 AM, 12:00 PM y 15:00 PM\n\n💰 EVALUACIONES CON COSTO ($30.000):\nCualquier horario fuera de los mencionados anteriormente.\n\n⚠️ IMPORTANTE: Informar al paciente sobre esta política al momento de agendar para evitar confusiones.` }
];

const paymentPolicies = [
    { title: "Protocolo de Cobro en Vivo", content: "1. Iniciar cordial: '¿Cómo te fue?'\n2. Informar valor COMPLETO: 'Ciento veinte mil pesos' (nunca solo el número)\n3. Preguntar medio: '¿Efectivo o tarjeta?'\n4. Despedida: 'Muchas gracias. En caso de cualquier duda, nos puedes contactar vía WhatsApp o llamado.'", type: "General" },
    { title: "Datos de Transferencia Cialo", content: "Centro Médico Cialo SPA\nRUT: 78.155.814-1\nBanco Santander — Cuenta Corriente Nº 0-000-9779419-7\nMail: pagos@cialo.cl\n\n📌 Obligatorio: solicitar a Natacha o Nicolás la revisión de la transferencia antes de confirmar la cita.", type: "General" },
    { title: "Datos de Transferencia Cialo Facial", content: "Cialo Facial SPA\nRUT: 78.024.821-1\nBanco Santander — Cuenta Corriente Nº 0000-9648-3139\nMail: pagos@cialo.cl\n\n📌 Obligatorio: solicitar a Natacha o Nicolás la revisión de la transferencia antes de confirmar la cita.", type: "General" },
    { title: "Datos de Transferencia Horus Skincare", content: "Horus Skincare\nRUT: 77.576.241-1\nBanco Santander — Cuenta Corriente Nº 87068706\nMail: pagos@cialo.cl\n\n📌 Para pagos de productos de vitrina.\n📌 Obligatorio: solicitar a Natacha o Nicolás la revisión de la transferencia antes de confirmar.", type: "General" },
    { title: "Link de Pago Clínica Cialo", content: "Para pagos de tratamientos de Clínica Cialo:\nmicrositios.getnet.cl/cialo\n\nEnviar este link al paciente para que realice el pago online de forma segura.", type: "General" },
    { title: "Link de Pago Cialo Facial", content: "Para pagos de tratamientos faciales:\nmicrositios.getnet.cl/cialofacial\n\nEnviar este link al paciente para que realice el pago online de forma segura.", type: "General" },
    { title: "Link de Pago Productos", content: "Para pagos de productos:\nmicrositios.getnet.cl/productocialo\n\nEnviar este link al paciente para que realice el pago de productos de forma segura.", type: "General" },
    { title: "Mensaje Base Confirmación", content: "(Nombre), quedó agendada tu cita con [PROFESIONAL] el día __ de __ a las __ horas.\nLa dirección es: Bulnes 220, oficina 509, Clínica Cialo – Edificio Puerto Mayor II, Los Ángeles\nAcá te dejamos un link con la ubicación: https://maps.app.goo.gl/PyeYcr4JdqW7iJ4G9\n\n[Insertar Política de Cancelación correspondiente]", type: "General" },
    { title: "Política Corporal", content: "Evaluación gratuita. Si cancelas con menos de 24 horas de anticipación, para reagendar se solicitará un abono de $10.000 vía transferencia. Este abono será descontado de tu presupuesto de tratamiento.", type: "Corporal" },
    { title: "Política Urología", content: "Cita $50.000 (Reembolsable). Pago el mismo día antes de ingresar. En caso de cancelar con menos de 24 horas o inasistencia sin aviso: para reagendar deberás pagar el valor de la consulta por anticipado vía transferencia.", type: "Medica" },
    { title: "Política Matrona", content: "Cita $30.000 (Reembolsable). En caso de cancelar con menos de 24 horas o inasistencia sin aviso: para reagendar deberás pagar el valor de la consulta por anticipado vía transferencia.", type: "Medica" },
    { title: "Política Dra. Kiss", content: "Evaluación gratuita. Si cancelas con menos de 24 horas de anticipación, para reagendar se solicitará un abono de $10.000 vía transferencia. Este abono será descontado de tu presupuesto de tratamiento.", type: "Estetica" },
    { title: "Política Dra. Araya", content: "Cita $40.000 (Reembolsable). Pago el mismo día antes de ingresar. En caso de cancelar con menos de 24 horas o inasistencia sin aviso: para reagendar deberás pagar el valor de la consulta por anticipado vía transferencia.", type: "Medica" },
    { title: "Política Dr. Luis Pérez", content: "Cita $40.000 (Reembolsable). Pago el mismo día antes de ingresar. En caso de cancelar con menos de 24 horas o inasistencia sin aviso: para reagendar deberás pagar el valor de la consulta por anticipado vía transferencia.", type: "Medica" }
];

const scriptsData = {
    Gestion: [
        { title: "Confirmación de Asistencia (Llamado 48hrs)", content: `"Hola, buenos días/buenas tardes, hablas con ___ de Clínica Cialo. Te llamaba para confirmar tu asistencia a tu cita con ___ el día ___ a las ___ horas.\n¿Confirmas tu asistencia?"`, note: "Realizar 48 horas antes. Máximo 2 intentos. Si no contesta, pasar a WhatsApp." },
        { title: "Confirmación WhatsApp (tras no contestar)", content: `"¡Hola! ¿Cómo estás? Te llamábamos desde Clínica Cialo para confirmar tu asistencia a tu cita con ___ el día ___ a las ___ horas.\n¿Confirmas tu cita? En caso de no poder asistir, agradeceríamos cancelarla con anticipación 🙏\nQuedo atenta a tu respuesta"` },
        { title: "Segundo Llamado + Mensaje Final (24hrs)", content: `"¡Hola! Hemos intentado comunicarnos contigo vía teléfono, correo y WhatsApp para confirmar tu asistencia a tu cita de mañana.\nAgradeceríamos mucho tu respuesta para que así no figures en nuestro sistema como inasistente sin previo aviso. 🙏"`, note: "Enviar solo si no respondió al primer WhatsApp. Realizar 24 horas antes." },
        { title: "Inasistencia (No Show)", content: `"Hola, ¿cómo estás? Te estuvimos esperando el día de hoy en tu cita.\n¿Ocurrió algo? ¿Te gustaría reagendar tu hora?"`, note: "Registrar como inasistente en Reservo. Si desea reagendar: Informar cobro de abono." },
        { title: "Cobro de Abono por Inasistencia", content: `"Para reagendar, el sistema nos solicita un abono previo debido a la inasistencia sin aviso.\nEste abono se descuenta del valor de tu consulta o del presupuesto de tu tratamiento el día de la cita.\n¿Deseas que te enviemos los datos para realizar la reserva?"\n\nAl reagendar informar: "Ud. puede realizar una modificación de la cita hasta 48 horas hábiles antes. En caso de cancelar después de ese plazo, el abono no es reembolsable."` },
        { title: "Solicitud de Boleta", content: `"¡Hola! Para emitir tu boleta necesitamos los siguientes datos:\n\n📋 Nombre completo\n📋 RUT\n📋 Correo electrónico\n📋 Dirección completa\n\nUna vez que nos envíes esta información, procesaremos tu boleta y te la enviaremos al correo indicado.\n\n¿Me podrías confirmar estos datos?"`, note: "Recopilar todos los datos antes de emitir la boleta." },
        { title: "Solicitud de Reembolso", content: `"¡Hola! Para procesar tu solicitud de reembolso con tu isapre o seguro, necesitamos emitir una boleta con los siguientes datos:\n\n📋 Nombre completo\n📋 RUT\n📋 Correo electrónico\n📋 Dirección completa\n\nLa boleta será enviada a tu correo y podrás presentarla directamente en tu isapre o seguro para solicitar el reembolso según tu plan de cobertura.\n\n¿Me podrías confirmar estos datos?"`, note: "Recordar que el reembolso depende del plan de cada paciente con su isapre/seguro." },
        { title: "Solicitud de Datos Completos", content: `"¡Hola! Para poder registrarte en nuestro sistema y agendar tu cita, necesito que me confirmes los siguientes datos:\n\n📋 Nombre completo\n📋 RUT\n📋 Correo electrónico\n📋 Teléfono de contacto\n\n¿Me podrías confirmar esta información?"`, note: "Usar para nuevos pacientes o actualización de datos." },
        { title: "Clausura por Reagendamientos Excesivos", content: `"Hola, ¿cómo estás? Te escribo porque hemos notado que has reagendado tu tratamiento en múltiples ocasiones.\n\nEntendemos que pueden surgir imprevistos, sin embargo, cada vez que reagendas, estamos bloqueando un cupo que otro paciente podría necesitar.\n\nPara poder continuar con tu tratamiento, necesitamos que confirmes una fecha definitiva y te comprometas a asistir. De lo contrario, lamentablemente tendremos que proceder con la clausura de tu tratamiento.\n\nEl valor pagado quedaría como crédito a favor para cuando estés en condiciones de retomar el tratamiento de forma comprometida.\n\n¿Podemos coordinar una fecha definitiva?"`, note: "Usar después de 3+ reagendamientos. Consultar con supervisor antes de enviar." },
        { title: "Cancelación Tardía (Tratamiento No Pagado)", content: `"Hola, hablas con Mónica de Clínica Cialo. Por políticas de nuestra clínica, si no te presentas a tu cita o cancelas con menos de 24 horas de anticipación, para reagendar se solicitará un abono de $10.000 vía transferencia. Este abono será descontado de tu presupuesto de tratamiento.\n\n¿Deseas que te enviemos los datos para realizar el abono y reagendar tu cita?"`, note: "Solo para tratamientos NO pagados. Si ya está pagado, usar otro protocolo." }
    ],
    Estetica: [
        { title: "Polinucleótidos (Dra. Kiss)", content: `En Clínica Cialo ofrecemos tratamientos con polinucleótidos, una de las terapias más avanzadas en bioestimulación y rejuvenecimiento cutáneo.\n\nSus principales beneficios son:\n✨ Estimulan la producción de colágeno y elastina, mejorando la firmeza y elasticidad de la piel.\n👁️ Reducen arrugas finas y ojeras en la zona periocular.\n🌟 Mejoran la calidad, textura e hidratación global de la piel cuando se aplican en full face.\n💎 Tratamiento seguro, biocompatible y con respaldo científico.\n\nValores por sesión:\n🔹 Zona periocular: $139.000\n🔹 Full face: $190.000\n\n¿Deseas que agendemos tu cita para comenzar tu tratamiento?` },
        { title: "Toxina Botulínica Dysport (Dra. Kiss)", content: `En Clínica Cialo realizamos tratamientos con toxina botulínica Dysport®, reconocida como una de las mejores y más seguras marcas del mundo, con amplio respaldo científico.\n\nSus beneficios incluyen:\n✨ Relajación de las arrugas dinámicas (frente, entrecejo, patas de gallo).\n🌟 Rejuvenecimiento natural, sin alterar la expresión.\n💎 Procedimiento rápido, seguro y con resultados progresivos en pocos días.\n\nValores Dra. Kiss:\n🔹 1 zona: $100.000\n🔹 Tercio superior (frente, entrecejo y patas de gallo): $179.000\n🔹 Full face (rostro completo): $329.000\n\n¿Quieres que coordinemos tu cita para el tratamiento?` },
        { title: "Relleno de Labios (Dra. Kiss)", content: `El valor del tratamiento de labios con Dra Mariane es de $180.000\n\nEs un tratamiento ambulatorio el cual se realiza bajo anestesia local.\nTrabajamos con marca Juvederm de Allergan, la marca de relleno más prestigiosa del mundo.\nLa durabilidad es de 8-12 meses aproximadamente en reabsorberse de manera completa.\n\n¿Desea ud una cita para el tratamiento?` },
        { title: "Ácido Hialurónico (Dra. Kiss)", content: `En Clínica Cialo realizamos tratamientos con ácido hialurónico de la más alta calidad, aplicados por la Dra. Mariane Kiss, especialista en medicina estética.\n\nCon este producto podemos abordar múltiples objetivos como relleno de labios, ojeras, surcos, perfilado mandibular, hidratación y armonización facial.\n\nEl valor de cada tratamiento con ácido hialurónico es de $180.000 por jeringa, ajustando la técnica y la cantidad según tus necesidades.\n\n¿Deseas que coordinemos tu cita con la Dra. Mariane Kiss para este procedimiento?` },
        { title: "CoolPeel (Láser CO2)", content: `Se trata de uno de los protocolos más avanzados en rejuvenecimiento facial no invasivo. Combinamos la última tecnología en láser de CO2 fraccionado superficial (CoolPeel) con exosomas de grado médico para:\n\n✅ Mejorar textura y poros dilatados\n✅ Aumentar luminosidad y firmeza de la piel\n✅ Estimular colágeno sin dañar capas profundas\n✅ Acelerar la recuperación postláser gracias a los exosomas\n\nEs ideal para quienes desean resultados visibles sin tiempos prolongados de reposo ni inflamación significativa.\n\n🔬 Trabajamos con tecnología TetraPro by DEKA, y exosomas Purasome NutriComplex, con evidencia clínica en regeneración dérmica.\n\nValor con Dra Mariane: $190.000 por sesión.\n\n¿Deseas una cita?` },
        { title: "Hilos Revitalizantes (Dra. Kiss)", content: `En Clínica Cialo ofrecemos tratamientos con hilos revitalizantes, realizados por la Dra. Mariane Kiss.\n\nEstos hilos tienen como objetivo estimular la producción natural de colágeno, mejorando la firmeza, textura y calidad de la piel de manera progresiva y natural.\n\nEl valor del tratamiento es de $120.000 por pack, lo que contempla la aplicación de 10 hilos revitalizantes.\n\n¿Deseas que coordinemos tu cita con la Dra. Kiss para este procedimiento?` },
        { title: "Promo Polinucleótidos + Botox", content: `En Clínica Cialo contamos con una promoción exclusiva realizada por la Dra. Mariane Kiss, especialista en medicina estética.\n\n✨ Polinucleótidos → estimulan la producción de colágeno y elastina, mejorando la firmeza, textura e hidratación de la piel.\n🌟 Toxina Botulínica Dysport® → relaja las arrugas dinámicas del tercio superior, logrando un resultado natural y armónico.\n\nValor promoción completa: $269.900\n\n¿Deseas que coordinemos tu cita con la Dra. Mariane Kiss para aprovechar esta combinación de tratamientos?` },
        { title: "Eliminación de Tatuajes", content: `El valor dependerá del tamaño y color del tatuaje. Si deseas puedes enviarme una fotografía para ayudarte en el valor por sesión 😊\n\n(REENVIAR FOTO A DR. NICOLÁS PARA VALOR)\n\nAl entregar presupuesto:\n"El valor de su tatuaje es de ____ por sesión.\n\nContamos con el láser Spectra XT, actualmente el mejor láser del mundo para remoción de tatuajes. Tiene un riesgo de cicatriz mucho menor que los demás láseres.\n\nLa cantidad de sesiones dependerá del tipo de tinta, profundidad, densidad, zona del cuerpo, cantidad de colores, metabolismo del paciente, hábitos, etc. Es difícil determinar una cantidad exacta, pero frecuentemente varían de 5 a 10 sesiones.\n\nLas sesiones se realizan cada 6 semanas, solo pagas la sesión a la que asistes.\n\n¿Desea ud una cita?"` },
        { title: "Sculptra (Bioestimulador)", content: `En Clínica Cialo ofrecemos tratamientos con Sculptra, el bioestimulador de colágeno más avanzado y duradero del mercado.\n\nSculptra es diferente a los rellenos tradicionales porque no solo rellena, sino que estimula la producción natural de colágeno de tu propia piel, logrando resultados progresivos, naturales y de larga duración.\n\nBeneficios principales:\n✨ Restaura el volumen facial perdido de forma gradual y natural\n🌟 Mejora la firmeza y elasticidad de la piel\n💎 Resultados que pueden durar hasta 2 años o más\n🎯 Ideal para rejuvenecimiento facial global, mejillas, sienes y mandíbula\n\nLa evaluación es gratuita para determinar el plan de tratamiento personalizado según tus necesidades.\n\n¿Deseas que agendemos tu evaluación con la Dra. Mariane Kiss?` }
    ],
    Corporal: [
        { title: "Depilación Láser (Soprano Titanium)", content: `En Clínica Cialo trabajamos con Soprano Titanium, considerado el gold standard en depilación láser a nivel mundial.\n\nEsta tecnología combina triple longitud de onda (Alexandrita, Diodo y Nd:YAG), lo que permite tratar todo tipo de pieles y vellos, incluso en pacientes morenos o con vellos resistentes.\n\nAdemás, cuenta con el sistema ICE Plus, un avanzado mecanismo de enfriamiento que protege la piel durante cada disparo, logrando un procedimiento seguro, eficaz y prácticamente indoloro.\n\nLa cantidad de sesiones dependerá de tu tipo de piel, grosor del vello y zona a tratar.\n\nLa evaluación es gratuita, para determinar el plan más adecuado para ti.\n\nPrecios: Tenemos valores tanto por sesión individual como en packs de varias sesiones, además de precios diferenciados según si deseas tratar una zona específica o varias zonas en conjunto.\n\n¿Tienes alguna zona en particular en mente para poder orientarte mejor?\n\nRecuerda que la evaluación es gratuita, donde podremos definir el plan ideal para ti según tu tipo de piel y vello.` },
        { title: "Tratamientos Reductivos", content: `Contamos con una amplia variedad de tratamientos corporales para reductivos, celulitis, estrías y flacidez, siempre ajustados a las necesidades de cada paciente, considerando la cantidad de grasa, IMC, tipo de piel y condiciones médicas.\n\nNuestros protocolos son totalmente personalizados y diseñados en base a una evaluación con nuestro equipo de profesionales.\n\nLa evaluación es gratuita, así podremos asesorarte sobre qué opción es la más adecuada para ti.\n\n¿Quieres que agendemos tu evaluación?` },
        { title: "Post-Láser (Venta Cruzada)", content: `(Preguntar proactivamente): "¿Quieres que te llevemos agua termal o Cicalfate para tu recuperación post láser?"\n\nLas cremas pueden cambiar según stock en vitrina.` },
        { title: "Exilis Ultra 360 (Radiofrecuencia)", content: `En Clínica Cialo contamos con Exilis Ultra 360, la tecnología más avanzada en radiofrecuencia monopolar para tratamientos corporales y faciales no invasivos.\n\nEsta tecnología combina radiofrecuencia y ultrasonido para:\n✨ Reducción de grasa localizada\n🔥 Tratamiento de celulitis\n💪 Reafirmación y tonificación de la piel\n🎯 Remodelación corporal sin cirugía\n\nEs un tratamiento completamente indoloro, sin tiempo de recuperación, que permite retomar actividades normales de inmediato.\n\nLa evaluación es gratuita para diseñar un protocolo personalizado según tus objetivos y zona a tratar.\n\n¿Quieres que agendemos tu evaluación?` },
        { title: "Clatuu (Criolipólisis)", content: `En Clínica Cialo ofrecemos Clatuu, tecnología de criolipólisis de última generación para eliminación de grasa localizada sin cirugía.\n\nClatuu utiliza frío controlado para cristalizar y eliminar las células grasas de forma definitiva, logrando una reducción visible y medible de grasa en las zonas tratadas.\n\nBeneficios principales:\n❄️ Eliminación definitiva de células grasas\n🎯 Ideal para abdomen, flancos, muslos, brazos y papada\n💎 Procedimiento no invasivo, sin agujas ni incisiones\n⏱️ Sin tiempo de recuperación\n📊 Resultados visibles desde la primera sesión, óptimos a los 2-3 meses\n\nLa evaluación es gratuita para determinar si eres candidato ideal y diseñar el plan de tratamiento.\n\n¿Deseas que agendemos tu evaluación?` }
    ],
    Nutricion: [
        { title: "Consulta Nutricional", content: `En Clínica Cialo contamos con 2 nutricionistas altamente calificados: Valentina Verdejo y Walter Zaror, especialistas en planificación personalizada y optimización de resultados.\n\nAdemás, disponemos de la calorimetría indirecta Q-NRG Max, tecnología de última generación que mide de forma precisa tu gasto energético en reposo. Con esta información podemos diseñar planes nutricionales y de entrenamiento totalmente personalizados, asegurando que tus resultados sean efectivos, medibles y sostenibles.\n\n✨ Esta combinación de especialistas + tecnología única en la ciudad convierte tu consulta en una experiencia mucho más completa que una visita nutricional convencional.\n\n¿Deseas que coordinemos tu consulta nutricional?` },
        { title: "Examen InBody 970", content: `En Clínica Cialo contamos con el único InBody 970 disponible en la ciudad, el analizador de composición corporal más avanzado del mundo.\n\nEste examen entrega un informe de 7 páginas con un desglose extremadamente preciso de tu cuerpo: masa muscular segmental, grasa visceral, distribución de líquidos, minerales, proteínas, metabolismo basal y mucho más.\n\nEs considerado el examen de composición corporal más completo del mundo, utilizado en centros médicos de alto nivel, hospitales universitarios y equipos de alto rendimiento deportivo.\n\nEn Cialo lo ponemos a tu disposición como herramienta clave para diseñar planes personalizados de nutrición, entrenamiento y salud.\n\nTienes dos formas de acceder al examen:\n🔹 Solo examen: $15.000 - Obtienes tu reporte completo con todos los indicadores.\n🔹 Examen + interpretación profesional: Incluido en la consulta nutricional ($40.000) - Recibirás evaluación completa, pauta personalizada y orientación profesional.\n\n¿Qué opción te acomoda más?` },
        { title: "Calorimetría Indirecta", content: `En Clínica Cialo contamos con la única Calorimetría Indirecta disponible en Los Ángeles, utilizando el equipo Q-NRG Max, considerado el más avanzado del mundo en este tipo de medición.\n\nEste examen permite conocer con exactitud tu gasto energético en reposo (metabolismo basal) y cómo tu cuerpo utiliza grasas, carbohidratos y proteínas como fuente de energía.\n\n🔹 Con esta información podemos diseñar planes nutricionales y de entrenamiento totalmente personalizados, evitando dietas genéricas y asegurando resultados efectivos, medibles y sostenibles en el tiempo.\n\nEl valor del examen es de $50.000 e incluye la interpretación profesional de los resultados.\n\n¿Deseas que coordinemos tu cita para realizar este examen?` }
    ],
    Medica: [
        { title: "Urología (Cita)", content: `En Clínica Cialo contamos con 2 especialistas certificados por CONACEM en Urología: el Dr. Guillermo Contreras y el Dr. Frank Ulloa.\n\nLa cita médica tiene un costo de $50.000, la cual puedes reembolsar con tu isapre o seguro, según tu plan. Este valor se cancela el mismo día de la consulta, antes de ingresar a la atención.\n\n⚠️ En caso de inasistencia sin aviso previo o cancelación con menos de 24 horas, para reagendar será necesario realizar el pago total anticipado vía transferencia al momento de reservar la nueva hora.\n\n¿Deseas que coordinemos tu horario?` },
        { title: "Agrandamiento de Pene", content: `El agrandamiento de pene es uno de los tratamientos más solicitados en Clínica Cialo, realizado exclusivamente por médico especialista en urología (no médicos generales).\n\nEl valor del tratamiento comienza desde $800.000, variando según el tamaño del miembro, la cantidad de relleno a aplicar, el número de sesiones y los objetivos de cada paciente.\n\n🔒 Toda tu información y antecedentes médicos son 100% confidenciales.\n\n¿Deseas que coordinemos una cita médica de evaluación para revisar tu caso en detalle?` },
        { title: "Matrona (Ginecoestética)", content: `En Clínica Cialo contamos con atención integral en el área femenina a cargo de nuestra matrona especialista, donde podrás resolver tanto aspectos de salud ginecológica como de bienestar íntimo y estético.\n\nEn tu consulta podemos abordar:\n🔹 Salud ginecológica general: controles, chequeos preventivos, orientación en métodos anticonceptivos, inserción y retiro de dispositivos intrauterinos (DIU/implantes).\n🔹 Salud sexual y reproductiva: planificación familiar, control de embarazo, educación en salud sexual.\n🔹 Ginecoestética y rejuvenecimiento íntimo femenino: tratamientos para mejorar tonicidad, lubricación, función y estética de la zona íntima.\n🔹 Peelings despigmentantes íntimos para tratar alteraciones de coloración.\n🔹 Asesoría personalizada para elegir los tratamientos y cuidados más adecuados para ti.\n\nLa consulta médica con nuestra matrona tiene un valor de $30.000, reembolsable con tu isapre o seguro según tu plan.\n\n⚠️ Políticas de cancelación: en caso de inasistencia sin aviso previo o cancelación con menos de 24 horas, para reagendar será necesario realizar el pago total anticipado vía transferencia.\n\n¿Deseas que coordinemos tu consulta con nuestra matrona?` },
        { title: "Láser CO2 Íntimo Femenino", content: `En Clínica Cialo realizamos tratamientos de rejuvenecimiento íntimo femenino con Láser CO₂ TetraPRO, una de las tecnologías más avanzadas y seguras disponibles a nivel mundial.\n\nEste procedimiento puede ayudar a mejorar:\n✨ Tonicidad y firmeza de la zona íntima.\n💧 Hidratación y lubricación natural.\n🌸 Función sexual y confort.\n🎯 Tratamiento de incontinencia leve y alteraciones postparto o por envejecimiento.\n\n📌 El valor del tratamiento se entrega solo tras la evaluación previa, ya que cada paciente requiere un protocolo distinto. La intensidad, número de sesiones y técnicas complementarias dependen de factores como:\n🔹 Antecedentes médicos y ginecológicos.\n🔹 Grado de laxitud o atrofia vaginal.\n🔹 Presencia de síntomas como resequedad, dolor o incontinencia.\n\nSolo una evaluación médica puede definir un presupuesto realista y seguro, ajustado a tus necesidades y objetivos.\n\n¿Deseas que agendemos tu consulta para evaluar si eres candidata a este procedimiento?` },
        { title: "Despigmentación Íntima Femenina", content: `En Clínica Cialo contamos con protocolos combinados de láser, peelings y tópicos para mejorar el tono de la zona íntima pigmentada.\n\nLa evaluación previa es fundamental para definir el presupuesto, ya que dependerá de:\n🔹 Tipo y origen del pigmento.\n🔹 Plan de tratamiento (peeling, láser, tópicos o combinación).\n🔹 Cantidad de sesiones según tu piel y la intensidad de la pigmentación.\n\n¿Deseas que coordinemos tu cita de evaluación para orientarte con el plan más adecuado?` },
        { title: "Salud Capilar (Dra. Javiera Araya)", content: `En Clínica Cialo contamos con la Dra. Javiera Araya, médico especialista en tricología (área médica enfocada en el estudio y tratamiento de la alopecia y otras alteraciones del cabello).\n\nCon ella podrás evaluar en detalle los distintos tipos de alopecia o caída del cabello, y acceder a un plan de tratamiento integral que puede incluir desde procedimientos mínimamente invasivos de restauración capilar hasta la cirugía de implante capilar, siempre ajustado a tus necesidades.\n\nLa consulta médica tiene un valor de $40.000, y puedes solicitar boleta reembolsable según la cobertura de tu isapre o seguro.\n\n⚠️ Políticas de cancelación: en caso de inasistencia sin aviso previo o cancelación con menos de 24 horas, para reagendar será necesario realizar el pago total anticipado vía transferencia al momento de reservar la nueva hora.\n\n¿Deseas que coordinemos tu consulta con la Dra. Araya?` },
        { title: "Implante Capilar (Dra. Araya)", content: `En Clínica Cialo la cirugía de implante capilar es realizada por un equipo de especialistas en restauración capilar.\n\nEl presupuesto se ajusta según la cantidad de unidades foliculares que sea necesario implantar. Esta cantidad se determina en la consulta médica, considerando:\n🔹 El grado de alopecia.\n🔹 La densidad y grosor del cabello.\n🔹 La calidad de las unidades foliculares presentes.\n\nDurante la consulta recibirás un pronóstico claro (si es necesario o no realizar el implante) y un presupuesto detallado de acuerdo a tu caso.\n\n¿Deseas que coordinemos tu cita de evaluación capilar?` },
        { title: "Onicomicosis (Tratamiento Láser)", content: `En Clínica Cialo ofrecemos tratamiento láser para onicomicosis (hongos en las uñas), una solución efectiva, segura y sin efectos secundarios.\n\nEl tratamiento con láser elimina los hongos de forma directa, penetrando en la uña sin dañar el tejido circundante.\n\nBeneficios del tratamiento:\n✨ Sin medicamentos orales ni efectos secundarios\n🎯 Procedimiento rápido e indoloro\n💎 Alta tasa de efectividad\n⏱️ Sin tiempo de recuperación\n🔬 Tecnología láser de última generación\n\nLa cantidad de sesiones dependerá del grado de afectación de las uñas, determinado en la evaluación médica.\n\nLa consulta médica tiene un valor de $40.000 (reembolsable).\n\n¿Deseas que coordinemos tu consulta para evaluar tu caso?` }
    ],
    Indicaciones: [
        { title: "Indicaciones Previas InBody 970", content: `📲 Para que el examen sea preciso y confiable, te pedimos considerar estas indicaciones:\n\n1. ⚖️ No comer ni beber (excepto agua) al menos 2 horas antes del examen.\n2. 🏃‍♂️ Evitar ejercicio intenso en las 12 horas previas.\n3. 🍷☕ No consumir alcohol ni cafeína 24 horas antes.\n4. 👚 Usar ropa ligera y cómoda, sin accesorios metálicos.\n5. 💧 Mantener una hidratación adecuada el día anterior.\n6. 👩‍🦰 Si eres mujer, idealmente realizar el examen fuera del periodo menstrual, ya que puede alterar los resultados por retención de líquidos.\n7. ⚠️ El examen no se realiza en embarazadas ni en personas con marcapasos o dispositivos electrónicos implantados.`, note: "Enviar una vez agendado el examen" },
        { title: "Indicaciones Previas Calorimetría Indirecta", content: `📲 Para obtener una medición precisa de tu metabolismo basal y gasto energético, sigue estas recomendaciones:\n\n1. 🌙 Ayuno mínimo de 6 horas antes del examen (solo se permite agua).\n2. 🛌 Descansar bien la noche anterior (evitar trasnocho).\n3. 🚭 No fumar al menos 4 horas antes.\n4. ☕🍵 Evitar cafeína, alcohol y estimulantes 24 horas previas.\n5. 🏃‍♂️ No realizar ejercicio intenso previo examen.`, note: "Enviar una vez agendado el examen" }
    ]
};
