/**
 * Catálogo de Tratamientos de Clínica Cialo
 * Información completa de cada tratamiento: nombre, descripción, profesional, precio, duración, etc.
 */

const tratamientosData = [
    // ==================== FACIAL - DR. NICOLÁS LAUCIRICA ====================
    {
        id: 'toxina-tercio-superior',
        categoria: 'Facial',
        subcategoria: 'Toxina Botulínica',
        nombre: 'Toxina Botulínica Tercio Superior',
        descripcion: 'Maneja tus arrugas y líneas de expresión en frente, entrecejo y patas de gallo.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 150000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '1 sesión (efecto 4-6 meses)',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'toxina-bruxismo',
        categoria: 'Facial',
        subcategoria: 'Toxina Botulínica',
        nombre: 'Toxina Botulínica Bruxismo',
        descripcion: 'Relaja maseteros, reduce tensión y suaviza el ángulo mandibular.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 200000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '1 sesión (efecto 4-6 meses)',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'toxina-sonrisa-gingival',
        categoria: 'Facial',
        subcategoria: 'Toxina Botulínica',
        nombre: 'Toxina Botulínica Sonrisa Gingival',
        descripcion: 'Modula la elevación labial para una sonrisa más armónica.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 100000,
        valorHasta: null,
        duracion: '20 min',
        sesiones: '1 sesión (efecto 4-6 meses)',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'toxina-full-face',
        categoria: 'Facial',
        subcategoria: 'Toxina Botulínica',
        nombre: 'Toxina Botulínica Full Face',
        descripcion: 'Mejora el tercio superior e inferior del rostro de forma integral.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 350000,
        valorHasta: null,
        duracion: '45 min',
        sesiones: '1 sesión (efecto 4-6 meses)',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'rinomodelacion',
        categoria: 'Facial',
        subcategoria: 'Ácido Hialurónico',
        nombre: 'Rinomodelación',
        descripcion: 'Mejora tu perfil nasal sin cirugía con ácido hialurónico.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 350000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: '1 sesión (duración 12-18 meses)',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'labios-ah',
        categoria: 'Facial',
        subcategoria: 'Ácido Hialurónico',
        nombre: 'Labios con Ácido Hialurónico',
        descripcion: 'Volumen, proyección, perfilado e hidratación labial.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 250000,
        valorHasta: 400000,
        duracion: '30 min',
        sesiones: '1 sesión (duración 8-12 meses)',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'menton-ah',
        categoria: 'Facial',
        subcategoria: 'Ácido Hialurónico',
        nombre: 'Mentón con Ácido Hialurónico',
        descripcion: 'Proyección y equilibrio del perfil facial.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 300000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '1 sesión (duración 12-18 meses)',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'pomulos-ah',
        categoria: 'Facial',
        subcategoria: 'Ácido Hialurónico',
        nombre: 'Pómulos con Ácido Hialurónico',
        descripcion: 'Soporte y efecto lifting del tercio medio facial.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 350000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: '1 sesión (duración 12-18 meses)',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'ojeras-ah',
        categoria: 'Facial',
        subcategoria: 'Ácido Hialurónico',
        nombre: 'Ojeras / Surco Lagrimal',
        descripcion: 'Mejora el hundimiento y el aspecto cansado del área periocular.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 300000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '1 sesión (duración 12-18 meses)',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'surco-nasogeniano-ah',
        categoria: 'Facial',
        subcategoria: 'Ácido Hialurónico',
        nombre: 'Surco Nasogeniano',
        descripcion: 'Suaviza surcos marcados nariz-boca.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 250000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '1 sesión (duración 8-12 meses)',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'definicion-mandibular',
        categoria: 'Facial',
        subcategoria: 'Ácido Hialurónico',
        nombre: 'Definición Mandibular',
        descripcion: 'Contorno mandibular más definido y juvenil.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 350000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: '1 sesión (duración 12-18 meses)',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'armonizacion-facial',
        categoria: 'Facial',
        subcategoria: 'Armonización',
        nombre: 'Armonización Facial',
        descripcion: 'Mejora globalmente el aspecto de tu rostro con técnicas combinadas.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 800000,
        valorHasta: 2500000,
        duracion: '60-90 min',
        sesiones: '1-3 sesiones según plan',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'sculptra',
        categoria: 'Facial',
        subcategoria: 'Bioestimuladores',
        nombre: 'Sculptra®',
        descripcion: 'Mejora calidad y densidad dérmica a mediano plazo estimulando colágeno.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 450000,
        valorHasta: null,
        duracion: '45 min',
        sesiones: '2-3 sesiones espaciadas',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'radiesse',
        categoria: 'Facial',
        subcategoria: 'Bioestimuladores',
        nombre: 'Radiesse®',
        descripcion: 'Efecto tensor inmediato y biorrevitalización a largo plazo.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 400000,
        valorHasta: null,
        duracion: '45 min',
        sesiones: '1-2 sesiones',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'ellanse',
        categoria: 'Facial',
        subcategoria: 'Bioestimuladores',
        nombre: 'Ellansé®',
        descripcion: 'Bioestímulo con duración extendida (1-4 años según tipo).',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 500000,
        valorHasta: null,
        duracion: '45 min',
        sesiones: '1 sesión',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'adn-salmon',
        categoria: 'Facial',
        subcategoria: 'Revitalización',
        nombre: 'ADN de Salmón',
        descripcion: 'Mejora hidratación, luminosidad y firmeza de la piel.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 180000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '3-4 sesiones',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'hilos-tensores',
        categoria: 'Facial',
        subcategoria: 'Hilos',
        nombre: 'Hilos Tensores y Revitalizantes',
        descripcion: 'Reafirman la piel, mejoran la flacidez y estimulan la producción de colágeno.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 350000,
        valorHasta: 1200000,
        duracion: '45-60 min',
        sesiones: '1 sesión',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'exosomas',
        categoria: 'Facial',
        subcategoria: 'Revitalización',
        nombre: 'Exosomas',
        descripcion: 'Regenera la piel, mejora textura e ilumina el rostro.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 250000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: '3-4 sesiones',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'hydrafacial',
        categoria: 'Facial',
        subcategoria: 'Dermatofuncional',
        nombre: 'HydraFacial® MD',
        descripcion: 'Limpieza profunda, extracción e hidratación con sueros activos.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 120000,
        valorHasta: null,
        duracion: '45-60 min',
        sesiones: 'Mensual recomendado',
        requiereEvaluacion: false,
        evaluacionGratuita: false
    },
    {
        id: 'hollywood-peel',
        categoria: 'Facial',
        subcategoria: 'Láser',
        nombre: 'Hollywood Peel',
        descripcion: 'Piel más luminosa, uniforme y con efecto glow instantáneo.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 150000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: '3-6 sesiones recomendadas',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'laser-melasma',
        categoria: 'Facial',
        subcategoria: 'Láser',
        nombre: 'Láser Melasma y Pigmentaciones',
        descripcion: 'Protocolos especializados para manchas hormonales.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 180000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: 'Según protocolo',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'blefaroplastia-laser',
        categoria: 'Facial',
        subcategoria: 'Láser',
        nombre: 'Blefaroplastía Láser',
        descripcion: 'Rejuvenecimiento de párpados con resultados naturales sin cirugía.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 400000,
        valorHasta: null,
        duracion: '45-60 min',
        sesiones: '1-2 sesiones',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },

    // ==================== CORPORAL - MARÍA JESÚS CONTRERAS ====================
    {
        id: 'depilacion-laser',
        categoria: 'Corporal',
        subcategoria: 'Depilación Láser',
        nombre: 'Depilación Láser Soprano Titanium',
        descripcion: 'Depilación definitiva con triple longitud de onda. Apta para todo tipo de piel.',
        profesional: 'María Jesús Contreras Merino',
        especialidad: 'Enfermera - Aparatología Estética',
        valorDesde: 25000,
        valorHasta: 350000,
        duracion: 'Según zona',
        sesiones: '6-10 sesiones',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'clatuu-alpha',
        categoria: 'Corporal',
        subcategoria: 'Criolipólisis',
        nombre: 'Clatuu Alpha - Criolipólisis',
        descripcion: 'Reducción de grasa localizada por congelamiento. Elimina hasta 25% de grasa.',
        profesional: 'María Jesús Contreras Merino',
        especialidad: 'Enfermera - Aparatología Estética',
        valorDesde: 180000,
        valorHasta: 350000,
        duracion: '45-60 min por zona',
        sesiones: '1-3 sesiones por zona',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'scizer',
        categoria: 'Corporal',
        subcategoria: 'Reducción de Grasa',
        nombre: 'Scizer HIFU Corporal',
        descripcion: 'Ultrasonido focalizado para reducción de grasa rebelde.',
        profesional: 'María Jesús Contreras Merino',
        especialidad: 'Enfermera - Aparatología Estética',
        valorDesde: 200000,
        valorHasta: null,
        duracion: '45-60 min',
        sesiones: '1-2 sesiones por zona',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'hifu-corporal',
        categoria: 'Corporal',
        subcategoria: 'Lifting Corporal',
        nombre: 'HIFU Ultraformer III Corporal',
        descripcion: 'Lifting sin cirugía para flacidez corporal.',
        profesional: 'María Jesús Contreras Merino',
        especialidad: 'Enfermera - Aparatología Estética',
        valorDesde: 250000,
        valorHasta: 600000,
        duracion: '45-90 min',
        sesiones: '1-2 sesiones anuales',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'morpheus8-corporal',
        categoria: 'Corporal',
        subcategoria: 'Radiofrecuencia',
        nombre: 'Morpheus8 Corporal',
        descripcion: 'Microagujas + radiofrecuencia para estrías, flacidez y remodelación.',
        profesional: 'María Jesús Contreras Merino',
        especialidad: 'Enfermera - Aparatología Estética',
        valorDesde: 300000,
        valorHasta: 600000,
        duracion: '45-60 min',
        sesiones: '3-4 sesiones',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'exilis-ultra',
        categoria: 'Corporal',
        subcategoria: 'Radiofrecuencia',
        nombre: 'Exilis Ultra 360',
        descripcion: 'Radiofrecuencia monopolar para reducción y tensado.',
        profesional: 'María Jesús Contreras Merino',
        especialidad: 'Enfermera - Aparatología Estética',
        valorDesde: 150000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: '4-6 sesiones',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'embody',
        categoria: 'Corporal',
        subcategoria: 'Tonificación',
        nombre: 'Embody - Tonificación Muscular',
        descripcion: 'Estimulación electromagnética para tonificar y fortalecer músculos.',
        profesional: 'María Jesús Contreras Merino',
        especialidad: 'Enfermera - Aparatología Estética',
        valorDesde: 80000,
        valorHasta: 150000,
        duracion: '30 min',
        sesiones: '8-12 sesiones',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },

    // ==================== CAPILAR - DRA. JAVIERA ARAYA ====================
    {
        id: 'consulta-tricologia',
        categoria: 'Capilar',
        subcategoria: 'Consulta',
        nombre: 'Consulta Tricológica',
        descripcion: 'Evaluación completa de salud capilar con tricoscopia y análisis clínico.',
        profesional: 'Dra. Javiera Araya Medina',
        especialidad: 'Tricóloga - Cirugía Capilar',
        valorDesde: 40000,
        valorHasta: null,
        duracion: '40 min',
        sesiones: 'Primera consulta',
        requiereEvaluacion: false,
        evaluacionGratuita: false
    },
    {
        id: 'mesoterapia-dutasteride',
        categoria: 'Capilar',
        subcategoria: 'Mesoterapia',
        nombre: 'Mesoterapia Dutasteride',
        descripcion: 'Tratamiento para alopecia androgenética masculina y femenina.',
        profesional: 'Dra. Javiera Araya Medina',
        especialidad: 'Tricóloga - Cirugía Capilar',
        valorDesde: 80000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: 'Mensual',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'mesoterapia-prp-capilar',
        categoria: 'Capilar',
        subcategoria: 'Mesoterapia',
        nombre: 'Mesoterapia PRP Capilar',
        descripcion: 'Plasma rico en plaquetas para estimulación del folículo piloso.',
        profesional: 'Dra. Javiera Araya Medina',
        especialidad: 'Tricóloga - Cirugía Capilar',
        valorDesde: 150000,
        valorHasta: null,
        duracion: '45 min',
        sesiones: 'Mensual por 4-6 meses',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'regenera',
        categoria: 'Capilar',
        subcategoria: 'Premium',
        nombre: 'REGENERA - Células Madre Capilares',
        descripcion: 'Tratamiento con células madre autólogas. ÚNICO EN CHILE exclusivo en Clínica Cialo.',
        profesional: 'Dra. Javiera Araya Medina',
        especialidad: 'Tricóloga - Cirugía Capilar',
        valorDesde: 1450000,
        valorHasta: null,
        duracion: '90 min',
        sesiones: '1 sesión (duración 2+ años)',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'implante-capilar',
        categoria: 'Capilar',
        subcategoria: 'Cirugía',
        nombre: 'Implante/Injerto Capilar',
        descripcion: 'Trasplante capilar FUE para restauración capilar permanente.',
        profesional: 'Dra. Javiera Araya Medina',
        especialidad: 'Tricóloga - Cirugía Capilar',
        valorDesde: 2500000,
        valorHasta: 5000000,
        duracion: '4-8 horas',
        sesiones: '1 cirugía',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },

    // ==================== UROLOGÍA - DR. CONTRERAS / DR. ULLOA ====================
    {
        id: 'bioplastia-pene',
        categoria: 'Urología',
        subcategoria: 'Estética Íntima',
        nombre: 'Bioplastía de Engrosamiento Peniano',
        descripcion: 'Aumento de grosor peniano con ácido hialurónico de alta densidad.',
        profesional: 'Dr. Guillermo Contreras / Dr. Frank Ulloa',
        especialidad: 'Urólogos',
        valorDesde: 500000,
        valorHasta: 800000,
        duracion: '60-90 min',
        sesiones: '1 procedimiento',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'circuncision',
        categoria: 'Urología',
        subcategoria: 'Cirugía',
        nombre: 'Circuncisión',
        descripcion: 'Cirugía ambulatoria bajo anestesia local para fimosis u otros.',
        profesional: 'Dr. Guillermo Contreras',
        especialidad: 'Urólogo',
        valorDesde: 450000,
        valorHasta: null,
        duracion: '45-60 min',
        sesiones: '1 cirugía',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'vasectomia',
        categoria: 'Urología',
        subcategoria: 'Cirugía',
        nombre: 'Vasectomía',
        descripcion: 'Método anticonceptivo permanente masculino.',
        profesional: 'Dr. Guillermo Contreras',
        especialidad: 'Urólogo',
        valorDesde: 400000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: '1 cirugía',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'frenuloplastia',
        categoria: 'Urología',
        subcategoria: 'Cirugía',
        nombre: 'Frenuloplastía',
        descripcion: 'Corrección del frenillo corto.',
        profesional: 'Dr. Guillermo Contreras',
        especialidad: 'Urólogo',
        valorDesde: 350000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '1 cirugía',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },

    // ==================== GINECOESTÉTICA - STEFANIA KUNCAR ====================
    {
        id: 'rejuvenecimiento-vaginal-laser',
        categoria: 'Ginecoestética',
        subcategoria: 'Láser',
        nombre: 'Rejuvenecimiento Vaginal Láser CO2',
        descripcion: 'Tratamiento láser para mejorar la elasticidad y lubricación vaginal.',
        profesional: 'Stefania Kuncar Ferrón',
        especialidad: 'Matrona - Ginecoestética',
        valorDesde: 250000,
        valorHasta: 350000,
        duracion: '30-45 min',
        sesiones: '3 sesiones',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'insercion-diu',
        categoria: 'Ginecoestética',
        subcategoria: 'Anticoncepción',
        nombre: 'Inserción DIU',
        descripcion: 'Colocación de dispositivo intrauterino (Mirena, Kyleena, T de Cobre).',
        profesional: 'Stefania Kuncar Ferrón',
        especialidad: 'Matrona - Ginecoestética',
        valorDesde: 40000,
        valorHasta: 60000,
        duracion: '20-30 min',
        sesiones: '1 procedimiento',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'insercion-implante',
        categoria: 'Ginecoestética',
        subcategoria: 'Anticoncepción',
        nombre: 'Inserción Implante Anticonceptivo',
        descripcion: 'Colocación de implante subdérmico anticonceptivo.',
        profesional: 'Stefania Kuncar Ferrón',
        especialidad: 'Matrona - Ginecoestética',
        valorDesde: 50000,
        valorHasta: null,
        duracion: '15-20 min',
        sesiones: '1 procedimiento',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },

    // ==================== NUTRICIÓN - VALENTINA / WALTER ====================
    {
        id: 'evaluacion-nutricional',
        categoria: 'Nutrición',
        subcategoria: 'Consulta',
        nombre: 'Evaluación Nutricional con InBody 970',
        descripcion: 'Evaluación completa con análisis de composición corporal profesional.',
        profesional: 'Valentina Verdejo / Walter Zaror',
        especialidad: 'Nutricionistas',
        valorDesde: 40000,
        valorHasta: 50000,
        duracion: '60 min',
        sesiones: 'Primera consulta',
        requiereEvaluacion: false,
        evaluacionGratuita: false
    },
    {
        id: 'calorimetria-indirecta',
        categoria: 'Nutrición',
        subcategoria: 'Exámenes',
        nombre: 'Calorimetría Indirecta',
        descripcion: 'Medición exacta del metabolismo basal para plan nutricional preciso.',
        profesional: 'Walter Zaror Maza',
        especialidad: 'Nutricionista Deportivo',
        valorDesde: 75000,
        valorHasta: 80000,
        duracion: '45 min',
        sesiones: '1 examen',
        requiereEvaluacion: false,
        evaluacionGratuita: false
    },

    // ==================== CIRUGÍA MAXILOFACIAL - DR. LUIS PÉREZ ====================
    {
        id: 'bichectomia',
        categoria: 'Cirugía Maxilofacial',
        subcategoria: 'Cirugía',
        nombre: 'Bichectomía',
        descripcion: 'Extracción de bolsas de Bichat para afinar el rostro.',
        profesional: 'Dr. Luis Pérez Lagos',
        especialidad: 'Cirujano Maxilofacial',
        valorDesde: 600000,
        valorHasta: null,
        duracion: '45-60 min',
        sesiones: '1 cirugía',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'blefaroplastia-quirurgica',
        categoria: 'Cirugía Maxilofacial',
        subcategoria: 'Cirugía',
        nombre: 'Blefaroplastía Quirúrgica',
        descripcion: 'Cirugía de párpados superior e inferior para rejuvenecimiento.',
        profesional: 'Dr. Luis Pérez Lagos',
        especialidad: 'Cirujano Maxilofacial',
        valorDesde: 800000,
        valorHasta: 1500000,
        duracion: '60-90 min',
        sesiones: '1 cirugía',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'otoplastia',
        categoria: 'Cirugía Maxilofacial',
        subcategoria: 'Cirugía',
        nombre: 'Otoplastía',
        descripcion: 'Corrección de orejas prominentes o en asa.',
        profesional: 'Dr. Luis Pérez Lagos',
        especialidad: 'Cirujano Maxilofacial',
        valorDesde: 700000,
        valorHasta: null,
        duracion: '60-90 min',
        sesiones: '1 cirugía',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },

    // ==================== VASCULAR - DRA. FRANCISCA GONZÁLEZ ====================
    {
        id: 'consulta-vascular',
        categoria: 'Vascular',
        subcategoria: 'Consulta',
        nombre: 'Consulta Vascular con Ecografía Doppler',
        descripcion: 'Evaluación vascular completa con ecografía incluida.',
        profesional: 'Dra. Francisca González Saldivia',
        especialidad: 'Cirujana Vascular',
        valorDesde: 50000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: 'Primera consulta',
        requiereEvaluacion: false,
        evaluacionGratuita: false
    },
    {
        id: 'escleroterapia-pequenas',
        categoria: 'Vascular',
        subcategoria: 'Escleroterapia',
        nombre: 'Escleroterapia Várices Pequeñas',
        descripcion: 'Tratamiento de arañitas vasculares y várices menores.',
        profesional: 'Dra. Francisca González Saldivia',
        especialidad: 'Cirujana Vascular',
        valorDesde: 80000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '2-4 sesiones',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'escleroterapia-grandes',
        categoria: 'Vascular',
        subcategoria: 'Escleroterapia',
        nombre: 'Escleroterapia Várices Grandes',
        descripcion: 'Tratamiento de várices de mayor calibre.',
        profesional: 'Dra. Francisca González Saldivia',
        especialidad: 'Cirujana Vascular',
        valorDesde: 400000,
        valorHasta: 500000,
        duracion: '45-60 min',
        sesiones: 'Según evaluación',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    }
];

// Obtener categorías únicas
function getCategoriasTratamientos() {
    const categorias = [...new Set(tratamientosData.map(t => t.categoria))];
    return categorias.sort();
}

// Obtener subcategorías por categoría
function getSubcategoriasTratamientos(categoria) {
    const subcats = [...new Set(tratamientosData.filter(t => t.categoria === categoria).map(t => t.subcategoria))];
    return subcats.sort();
}
