/**
 * Catálogo de Tratamientos de Clínica Cialo
 * Información completa de cada tratamiento: nombre, descripción, profesional, precio, duración, etc.
 */

const tratamientosData = [
    // ==================== FACIAL - DR. NICOLÁS LAUCIRICA ====================
    {
        id: 'toxina-tercio-superior',
        categoria: 'Facial',
        subcategoria: 'Toxina Botulínica',
        nombre: 'Toxina Botulínica Tercio Superior Facial',
        descripcion: 'Procedimiento inyectable que utiliza toxina botulínica tipo A para relajar temporalmente los músculos responsables de arrugas dinámicas del tercio superior (frente, glabela/entrecejo y líneas perioculares). Reduce líneas de expresión, suaviza la apariencia del rostro y previene el envejecimiento prematuro. Dirigido a mujeres y hombres que buscan un resultado natural, preventivo o correctivo, con seguridad y respaldo científico.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 210000,
        valorFidelizacion: 189000,
        valorHasta: null,
        duracion: '20 min',
        sesiones: '1 sesión (efecto 4-6 meses)',
        protocolo: 'Repetir cada 4–6 meses. Control a los 10–14 días para ajustes. Uso preventivo en pacientes jóvenes.',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'toxina-bruxismo',
        categoria: 'Facial',
        subcategoria: 'Toxina Botulínica',
        nombre: 'Toxina Botulínica Bruxismo (Maseteros)',
        descripcion: 'Tratamiento inyectable que utiliza toxina botulínica tipo A para disminuir la hiperactividad del músculo masetero, responsable del apretamiento dental nocturno (bruxismo), dolor mandibular, desgaste dentario y sobrecarga articular. Al reducir la fuerza muscular, disminuyen las contracturas, el dolor, los daños en piezas dentales y la cefalea tensional. Además, en pacientes con hipertrofia masetérica genera un efecto estético secundario de afinamiento mandibular.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 200000,
        valorHasta: null,
        duracion: '20 min',
        sesiones: '1 sesión (efecto 4-6 meses)',
        protocolo: 'Repetir cada 4–6 meses en bruxismo activo. Primeros 2–3 ciclos pueden requerir intervalos más cercanos (3–4 meses). Resultado funcional entre 7–14 días.',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'toxina-sonrisa-gingival',
        categoria: 'Facial',
        subcategoria: 'Toxina Botulínica',
        nombre: 'Toxina Botulínica Sonrisa Gingival',
        descripcion: 'Corrección de la sonrisa gingival mediante toxina botulínica. Modula la elevación del labio superior para reducir la exposición excesiva de encía al sonreír. Tratamiento sutil que logra una sonrisa más armónica y natural. Procedimiento rápido con resultados visibles en pocos días.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 100000,
        valorHasta: null,
        duracion: '20 min',
        sesiones: '1 sesión (efecto 4-6 meses)',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'toxina-full-face',
        categoria: 'Facial',
        subcategoria: 'Toxina Botulínica',
        nombre: 'Toxina Botulínica Full Face',
        descripcion: 'Tratamiento integral que utiliza toxina botulínica tipo A para relajar selectivamente los músculos responsables de arrugas dinámicas en todo el rostro. Incluye tercio superior (frente, entrecejo, patitas de gallo) y zonas avanzadas como líneas de conejo (bunny lines), mentonianos, depresor del ángulo de la boca (DAO) para suavizar aspecto de tristeza, y puntos estratégicos en la línea mandibular (jowls) para mejorar definición. Dirigido a mujeres y hombres que buscan una armonización global y resultados naturales.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 329000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '1 sesión (efecto 4-6 meses)',
        protocolo: 'Cada 4 a 6 meses según necesidad y grado de contracción muscular.',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'toxina-espasmos-paralisis',
        categoria: 'Facial',
        subcategoria: 'Toxina Botulínica',
        nombre: 'Toxina Botulínica Espasmos Faciales y Parálisis',
        descripcion: 'Procedimiento terapéutico avanzado que utiliza toxina botulínica tipo A para modular la actividad muscular en pacientes con espasmos hemifaciales, sincinesias, hiperactividad compensatoria o secuelas funcionales de parálisis facial. La toxina actúa reduciendo contracciones involuntarias, aliviando dolor, mejorando la simetría facial y disminuyendo movimientos anómalos asociados a la reinervación aberrante.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: null,
        valorHasta: null,
        duracion: '20-30 min',
        sesiones: 'Según evaluación',
        protocolo: 'Cada 3–4 meses según severidad. Control a las 2 semanas para evaluar simetría y ajustes.',
        requiereEvaluacion: true,
        evaluacionGratuita: false,
        notas: 'Precio variable según cantidad de unidades y músculos afectados. Evaluación presencial requerida.'
    },
    {
        id: 'rinomodelacion',
        categoria: 'Facial',
        subcategoria: 'Ácido Hialurónico',
        nombre: 'Rinomodelación',
        descripcion: 'Remodelación nasal sin cirugía mediante ácido hialurónico. Permite corregir imperfecciones como dorso irregular, punta caída, asimetrías o pequeñas desviaciones. Mejora el perfil nasal de forma inmediata con resultados naturales. Procedimiento ambulatorio, reversible y sin tiempo de recuperación. Alternativa ideal para quienes buscan mejorar su nariz sin someterse a rinoplastia quirúrgica.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 350000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: '1 sesión (duración 12-18 meses)',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'labios-ah',
        categoria: 'Facial',
        subcategoria: 'Ácido Hialurónico',
        nombre: 'Relleno de Labios con Ácido Hialurónico',
        descripcion: 'Procedimiento inyectable que utiliza ácido hialurónico de alta calidad para definir el contorno labial, mejorar volumen, hidratar profundamente y armonizar la proporción entre labio superior e inferior. Permite corregir asimetrías, recuperar estructura perdida por envejecimiento y potenciar la naturalidad del rostro. Procedimiento realizado bajo anestesia local.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 240000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '1 sesión (duración 10-14 meses)',
        protocolo: 'Control a los 10–14 días para evaluar integración y asimetrías.',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'menton-ah',
        categoria: 'Facial',
        subcategoria: 'Ácido Hialurónico',
        nombre: 'Relleno de Mentón con Ácido Hialurónico',
        descripcion: 'Procedimiento inyectable que utiliza ácido hialurónico de alta densidad para proyectar, alargar o definir el mentón, mejorando el balance del perfil facial y la relación entre nariz, labios y línea mandibular. Ayuda a corregir retrognatia leve, aumentar la proyección anterior, crear un contorno más armónico y mejorar la definición del tercio inferior.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 220000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '1 sesión (duración 12-18 meses)',
        protocolo: 'El valor por jeringa disminuye si es necesario aplicar más de 1 ml en la misma sesión.',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'pomulos-ah',
        categoria: 'Facial',
        subcategoria: 'Ácido Hialurónico',
        nombre: 'Relleno de Pómulos / Tercio Medio Facial con Ácido Hialurónico',
        descripcion: 'Procedimiento estructural avanzado que utiliza ácido hialurónico de alta cohesividad para restaurar el soporte profundo del tercio medio del rostro. Repone volumen perdido por envejecimiento, mejora la proyección del pómulo, reposiciona tejidos descendidos y reduce indirectamente la marcación del surco nasogeniano. Uno de los tratamientos más importantes en armonización facial.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 200000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '1 sesión (duración 12-18 meses)',
        protocolo: 'Cada 12 a 18 meses según necesidad.',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'fosa-temporal-ah',
        categoria: 'Facial',
        subcategoria: 'Ácido Hialurónico',
        nombre: 'Relleno de Fosa Temporal con Ácido Hialurónico',
        descripcion: 'Procedimiento estructural avanzado que utiliza ácido hialurónico de alta densidad para corregir la pérdida de volumen en la fosa temporal. Este hundimiento ocurre por reabsorción ósea, pérdida de grasa profunda y cambios ligamentarios asociados al envejecimiento. Su reposición mejora la proyección lateral de la ceja, suaviza la transición frente–pómulo y recupera el contorno tridimensional del tercio superior.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 220000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '1 sesión (duración 12-18 meses)',
        protocolo: 'Duración promedio 12–18 meses según tipo de AH y grado de depresión temporal.',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'ojeras-ah',
        categoria: 'Facial',
        subcategoria: 'Ácido Hialurónico',
        nombre: 'Ojeras / Surco Lagrimal',
        descripcion: 'Tratamiento del surco lagrimal y ojeras hundidas con ácido hialurónico específico para esta delicada zona. Mejora el aspecto cansado, reduce la sombra oscura bajo los ojos y suaviza el hundimiento. Requiere técnica especializada por ser una zona muy vascularizada. Resultados sutiles pero transformadores que devuelven frescura a la mirada.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 300000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '1 sesión (duración 12-18 meses)',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'surco-nasogeniano-ah',
        categoria: 'Facial',
        subcategoria: 'Ácido Hialurónico',
        nombre: 'Relleno de Surco Nasogeniano con Ácido Hialurónico',
        descripcion: 'Procedimiento complementario que utiliza ácido hialurónico de mediana a alta densidad para suavizar la profundidad del surco nasogeniano. Este pliegue es consecuencia de pérdida de soporte malar, descenso ligamentario y flacidez. El relleno directo se usa para refinar el resultado, pero no reemplaza terapias estructurales como pómulos, lifting vectorial, Sculptra o Radiesse.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 200000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '1 sesión (duración 12-18 meses)',
        protocolo: 'Cada 12 a 18 meses según necesidad. Requiere soporte estructural previo.',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'definicion-mandibular',
        categoria: 'Facial',
        subcategoria: 'Ácido Hialurónico',
        nombre: 'Relleno y Perfilado de Borde Mandibular con Ácido Hialurónico',
        descripcion: 'Procedimiento estructural que utiliza ácido hialurónico de alta densidad para definir y proyectar la línea mandibular, delineando un contorno más marcado, simétrico y armónico con el resto del rostro. Permite mejorar el ángulo mandibular, disimular flacidez leve del tercio inferior, corregir asimetrías y dar una apariencia más firme y definida. Dirigido tanto a hombres como mujeres.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 200000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '1 sesión (duración 12-18 meses)',
        protocolo: 'Retoques periódicos para mantener resultados. Cantidad de AH según biotipo facial e IMC.',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'bichectomia-laucirica',
        categoria: 'Facial',
        subcategoria: 'Cirugía',
        nombre: 'Cirugía de Bichectomía',
        descripcion: 'Procedimiento quirúrgico ambulatorio que consiste en la resección parcial y controlada de las bolas de Bichat, estructuras grasas profundas ubicadas en la mejilla. Su objetivo es mejorar la definición del tercio medio e inferior del rostro, proyectando mayor contorno mandibular y afinando la parte central de la cara. Técnica conservadora priorizando seguridad, función y naturalidad.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 300000,
        valorHasta: null,
        duracion: '60 min',
        sesiones: '1 única vez',
        protocolo: 'Control postquirúrgico a los 7-10 días. Resultados definitivos entre 3-6 meses. Incluye faja compresora y derecho a pabellón.',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'armonizacion-facial',
        categoria: 'Facial',
        subcategoria: 'Armonización',
        nombre: 'Armonización Facial',
        descripcion: 'Conjunto de tratamientos diseñados para equilibrar, rejuvenecer y potenciar la estética global del rostro de manera natural y proporcional. Analiza el rostro como una unidad funcional y tridimensional, identificando puntos de soporte, áreas de envejecimiento y necesidades estructurales. Puede incluir ácido hialurónico, toxina botulínica, bioestimuladores, láser, lifting vectorial y otras terapias según diagnóstico.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: null,
        valorHasta: null,
        duracion: '30-60 min',
        sesiones: '1-2 sesiones iniciales',
        protocolo: 'Mantención: fillers cada 12-18 meses, toxina cada 4-6 meses, bioestimuladores cada 6-12 meses. Plan completamente personalizado.',
        requiereEvaluacion: true,
        evaluacionGratuita: true,
        notas: 'Precio variable según zonas a tratar, grado de envejecimiento y objetivos del paciente.'
    },
    {
        id: 'sculptra',
        categoria: 'Facial',
        subcategoria: 'Bioestimuladores',
        nombre: 'Sculptra®',
        descripcion: 'Bioestimulador avanzado compuesto por ácido poli-L-láctico (PLLA), diseñado para inducir la producción natural de colágeno tipo I y III. No actúa como un relleno inmediato, sino que estimula la capacidad regenerativa de la piel, mejorando firmeza, densidad dérmica, elasticidad y contorno facial a largo plazo. Indicado para rejuvenecimiento natural y progresivo del rostro y cuello.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 500000,
        valorHasta: null,
        duracion: '30-40 min',
        sesiones: '2-3 sesiones separadas por 3 meses',
        protocolo: 'Mantención cada 6 meses. Resultado inicia a las 8–12 semanas, progresivo hasta los 9–12 meses.',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'radiesse',
        categoria: 'Facial',
        subcategoria: 'Bioestimuladores',
        nombre: 'Radiesse® – Bioestimulación con Hidroxiapatita de Calcio',
        descripcion: 'Bioestimulador compuesto por microesferas de hidroxiapatita de calcio suspendidas en un gel, diseñado para estimular la producción natural de colágeno y elastina. Entrega un doble beneficio: efecto inmediato de soporte y resultado progresivo a medida que el organismo genera nuevo colágeno. Ideal para mejorar firmeza, definición de contornos, calidad de piel y sostén profundo en rostro, cuello y zonas corporales.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 400000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '1-2 sesiones (duración 12-18 meses)',
        protocolo: 'Cada 6 a 12 meses según necesidad y grado de flacidez.',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'ellanse',
        categoria: 'Facial',
        subcategoria: 'Bioestimuladores',
        nombre: 'Ellansé®',
        descripcion: 'Bioestimulador de policaprolactona (PCL) que combina relleno inmediato con bioestimulación prolongada. Disponible en diferentes duraciones (S, M, L, E) según las necesidades del paciente, con efectos que pueden durar de 1 a 4 años. Ideal para quienes buscan resultados duraderos y naturales sin necesidad de retoques frecuentes.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 500000,
        valorHasta: null,
        duracion: '45 min',
        sesiones: '1 sesión',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'adn-salmon',
        categoria: 'Facial',
        subcategoria: 'Bioregeneración',
        nombre: 'Polinucleótidos Perioculares / ADN de Salmón',
        descripcion: 'Tratamiento bioregenerativo que utiliza polinucleótidos purificados con alta capacidad de estimular fibroblastos, aumentar síntesis de colágeno y mejorar la hidratación profunda en el área periocular. Reduce apariencia de cansancio, atenúa líneas finas, disminuye laxitud leve y mejora textura. No rellena volumen: regenera la piel desde adentro.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 139000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '3 sesiones separadas por 1 mes',
        protocolo: 'Resultados desde la segunda sesión. Mantención cada 6 meses según calidad de piel.',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'adn-salmon-fullface',
        categoria: 'Facial',
        subcategoria: 'Bioregeneración',
        nombre: 'Polinucleótidos Full Face / ADN de Salmón',
        descripcion: 'Tratamiento bioregenerativo avanzado que utiliza polinucleótidos purificados para mejorar globalmente la calidad de la piel del rostro. Estimula fibroblastos, aumenta síntesis de colágeno y elastina, mejora hidratación profunda y optimiza densidad dérmica. Complemento ideal a bioestimuladores estructurales (Sculptra, Radiesse) o tratamientos de tensado facial.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 190000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '3 sesiones separadas por 1 mes',
        protocolo: 'Efecto progresivo que se potencia con el tiempo. Mantención cada 6 meses.',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'hilos-tensores',
        categoria: 'Facial',
        subcategoria: 'Hilos',
        nombre: 'Hilos Tensores y Revitalizantes',
        descripcion: 'Tratamiento de lifting sin cirugía mediante hilos de PDO (polidioxanona) o PLLA. Los hilos tensores reposicionan tejidos caídos (papada, mejillas, cejas), mientras los hilos revitalizantes estimulan colágeno mejorando la calidad de la piel. Procedimiento mínimamente invasivo con resultados inmediatos que mejoran progresivamente.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 350000,
        valorHasta: 1200000,
        duracion: '45-60 min',
        sesiones: '1 sesión',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'exosomas',
        categoria: 'Facial',
        subcategoria: 'Bioregeneración',
        nombre: 'Exosomas Purasomes (Aprobado FDA)',
        descripcion: 'Nanopartículas bioactivas derivadas de células madre mesenquimales, capaces de modular inflamación, estimular fibroblastos, mejorar matriz extracelular y potenciar regeneración cutánea. Actúan como mensajeros celulares que activan procesos de reparación profunda. Beneficios en luminosidad, textura, firmeza, reducción de poros y recuperación acelerada post-láser.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 200000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '3 sesiones cada 4 semanas',
        protocolo: 'Mantención cada 3-6 meses. Puede combinarse con láser CO₂, Morpheus8, Sculptra, Radiesse.',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'hydrafacial',
        categoria: 'Facial',
        subcategoria: 'Dermatofuncional',
        nombre: 'HydraFacial MD',
        descripcion: 'Procedimiento dermatofuncional avanzado que combina limpieza profunda, exfoliación controlada, extracción indolora, hidratación intensiva y aporte de antioxidantes mediante tecnología de vórtex patentada. En Cialo trabajamos exclusivamente con el equipo Hydrafacial MD original. Mejora luminosidad, textura, hidratación y claridad de la piel desde la primera sesión.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 75000,
        valorHasta: null,
        duracion: '60 min',
        sesiones: 'Según condición cutánea',
        protocolo: 'Mantención: cada 4-8 semanas. Piel acneica: cada 2-4 semanas. Preparación pre-tratamientos: 7-10 días antes.',
        requiereEvaluacion: false,
        evaluacionGratuita: false
    },
    {
        id: 'hollywood-peel',
        categoria: 'Facial',
        subcategoria: 'Láser',
        nombre: 'Hollywood Peel',
        descripcion: 'Tratamiento láser con carbón activado que proporciona un efecto glow instantáneo. El láser Nd:YAG calienta las partículas de carbón aplicadas sobre la piel, logrando limpieza profunda de poros, reducción de puntos negros, estimulación de colágeno y una piel más luminosa y uniforme. Llamado así porque es el favorito de las celebridades antes de eventos.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 150000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: '3-6 sesiones recomendadas',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'coolpeel-exosomas',
        categoria: 'Facial',
        subcategoria: 'Láser',
        nombre: 'CoolPeel + Exosomas (TetraPro CO₂ + Purasome)',
        descripcion: 'Protocolo de rejuvenecimiento facial no invasivo que combina CoolPeel, técnica avanzada de láser CO₂ fraccionado superficial con mínima ablación térmica, junto a exosomas Purasome NutriComplex con evidencia científica en regeneración dérmica. Potencia estimulación de colágeno, mejora textura, reduce poros, aumenta luminosidad y acelera recuperación postláser.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 200000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '3 sesiones cada 4 semanas',
        protocolo: 'Mejoría progresiva desde primera sesión. Mantención cada 3-6 meses según calidad dérmica.',
        requiereEvaluacion: true,
        evaluacionGratuita: true,
        notas: 'Valor de oferta'
    },
    {
        id: 'laser-melasma',
        categoria: 'Facial',
        subcategoria: 'Láser',
        nombre: 'Tratamiento para Melasma',
        descripcion: 'Condición pigmentaria compleja que requiere enfoque altamente personalizado. Protocolos integrales basados en evidencia científica, combinando tecnologías láser de última generación, cosmética médica individualizada, medicación oral/tópica cuando corresponde, fotoprotección avanzada y asesoría en hábitos para minimizar recidivas.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: null,
        valorHasta: null,
        duracion: '30 min',
        sesiones: 'Múltiples sesiones cada 2-4 semanas',
        protocolo: 'Manejo continuo con mantención. Combina láser + rutina médica + medicación según necesidad. Especial cuidado en períodos de exposición UV.',
        requiereEvaluacion: true,
        evaluacionGratuita: false,
        notas: 'No se entrega presupuesto sin evaluación previa. Plan según tipo de melasma, extensión, profundidad y fototipo.'
    },
    {
        id: 'laser-pigmentaciones',
        categoria: 'Facial',
        subcategoria: 'Láser',
        nombre: 'Tratamiento Láser para Pigmentaciones y Manchas',
        descripcion: 'Pigmentaciones de múltiples orígenes: daño solar, pecas, lentigos, melanosis postinflamatoria, hiperpigmentación por fricción. Más de 12 tecnologías láser y luz disponibles: Q-Switched, fraccionado, IPL M22, CO₂ superficial, fototerapia. Selección de terapia exacta según tipo de mancha, profundidad y fototipo.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: null,
        valorHasta: null,
        duracion: '30-60 min',
        sesiones: '1-6 sesiones cada 3-6 semanas',
        protocolo: 'Manchas superficiales responden más rápido; profundas requieren protocolos combinados.',
        requiereEvaluacion: true,
        evaluacionGratuita: false,
        notas: 'Tratamiento definido exclusivamente tras evaluación médica especializada.'
    },
    {
        id: 'laser-flacidez-facial',
        categoria: 'Facial',
        subcategoria: 'Láser',
        nombre: 'Tratamiento Láser para Flacidez Facial',
        descripcion: 'Flacidez multifactorial que afecta piel y tejidos de soporte. Tecnologías: CO₂ fraccionado superficial/profundo, láser no ablativo, radiofrecuencia fraccionada, energía térmica controlada y bioestimulación. Selección según grado de flacidez, fototipo, espesor cutáneo y tiempo de recuperación. Estimula colágeno, mejora tensión y redefine contornos.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: null,
        valorHasta: null,
        duracion: '30-60 min',
        sesiones: 'Según protocolo definido en evaluación',
        protocolo: 'Personalizado según grado de flacidez, tecnologías, profundidad y tiempos de recuperación.',
        requiereEvaluacion: true,
        evaluacionGratuita: false,
        notas: 'Presupuesto tras evaluación. Precio según tecnologías necesarias y área involucrada.'
    },
    {
        id: 'laser-rosacea',
        categoria: 'Facial',
        subcategoria: 'Láser',
        nombre: 'Láser Vascular para Rosácea',
        descripcion: 'Tratamiento dermatológico avanzado que utiliza distintas tecnologías láser para disminuir enrojecimiento, telangiectasias, inflamación y brotes asociados a la rosácea. Protocolos integrales que combinan láser vascular selectivo, cuidados cosméticos específicos y asesoría en hábitos. Tratamiento personalizado según subtipo de rosácea.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: null,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '3-5 sesiones cada 4 semanas',
        protocolo: 'Mantención según subtipo de rosácea. Contamos con 4 tipos de láser vascular.',
        requiereEvaluacion: true,
        evaluacionGratuita: false,
        notas: 'Precio determinado en evaluación según tipo de rosácea, fototipo y tecnología a utilizar.'
    },
    {
        id: 'laser-cicatrices-acne',
        categoria: 'Facial',
        subcategoria: 'Láser',
        nombre: 'Cicatrices de Acné con Láser',
        descripcion: 'Tratamiento personalizado para cicatrices de acné (rolling, ice-pick, boxcar, hipertróficas, atróficas). Trabajamos con TetraPro CO₂, CO₂RE, láseres no ablativos, radiofrecuencia fraccionada Morpheus8, subcisión y técnicas combinadas. Plan según subtipo, profundidad, densidad, fototipo y tiempo de recuperación disponible.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: null,
        valorHasta: null,
        duracion: '30-60 min',
        sesiones: '3-6 sesiones cada 4-8 semanas',
        protocolo: 'Algunos casos requieren combinaciones en misma sesión (láser + subcisión + bioestimulación). Más de 30 protocolos disponibles.',
        requiereEvaluacion: true,
        evaluacionGratuita: false,
        notas: 'Precio determinado en evaluación según tipo y severidad de cicatrices, tecnologías necesarias y número de sesiones.'
    },
    {
        id: 'laser-co2-resurfacing',
        categoria: 'Facial',
        subcategoria: 'Láser',
        nombre: 'Láser CO₂ Full Resurfacing',
        descripcion: 'Procedimiento de rejuvenecimiento ablativo o subablativo que utiliza energía CO₂ fraccionada para tratar arrugas finas y moderadas, líneas perioculares, poros dilatados, cicatrices, daño solar y textura irregular. Renovación profunda de piel y estimulación intensa de colágeno. Plataformas TetraPro by DEKA y CO₂RE con profundidad y densidad adaptables.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 200000,
        valorHasta: null,
        duracion: '30-60 min',
        sesiones: '1-3 sesiones cada 1-2 meses',
        protocolo: 'Downtime 3-7 días según profundidad. Mantención anual según envejecimiento cutáneo.',
        requiereEvaluacion: true,
        evaluacionGratuita: false,
        notas: 'Valor exacto tras evaluación clínica según protocolo, profundidad, área y tecnología.'
    },
    {
        id: 'morpheus8-facial',
        categoria: 'Facial',
        subcategoria: 'Radiofrecuencia',
        nombre: 'Morpheus 8 Facial',
        descripcion: 'Plataforma de radiofrecuencia fraccionada más prestigiosa y avanzada, combinando microagujas con energía térmica profunda para estimular colágeno, tensar tejidos y mejorar la calidad global de la piel. Trabaja distintas profundidades abordando flacidez leve a moderada, poros dilatados, líneas finas y textura irregular. Dr. Laucirica: primer profesional con Morpheus8 en el sur de Chile.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: null,
        valorHasta: null,
        duracion: '60 min',
        sesiones: '3-4 sesiones cada 4-6 semanas',
        protocolo: 'Personalizado según zona, profundidad PIN, energía, grado de flacidez. Posibilidad de combinar activos/vitaminas. Mantención anual.',
        requiereEvaluacion: true,
        evaluacionGratuita: false,
        notas: 'Precio según zonas, profundidad, energía, número de pasadas y objetivo del paciente.'
    },
    {
        id: 'laser-resurfx',
        categoria: 'Facial',
        subcategoria: 'Láser',
        nombre: 'Láser ResurFX',
        descripcion: 'Láser no ablativo fraccionado para mejorar textura, poros dilatados, marcas postacné, líneas finas y calidad dérmica. No remueve capas de piel: menor tiempo de recuperación con potente estimulación de colágeno. Parámetros personalizables: densidad, energía, profundidad y patrones. Ideal entre tratamientos suaves y CO₂ para mejoría visible con downtime acotado.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: null,
        valorHasta: null,
        duracion: '30-60 min',
        sesiones: '3-5 sesiones cada 3-4 semanas',
        protocolo: 'Estimulación de colágeno progresiva, resultados notorios desde segunda sesión. Mantención anual opcional.',
        requiereEvaluacion: true,
        evaluacionGratuita: false,
        notas: 'Valor según área, energía, densidad, profundidad, objetivos y complejidad del protocolo.'
    },
    {
        id: 'hialuronidasa',
        categoria: 'Facial',
        subcategoria: 'Corrección',
        nombre: 'Aplicación de Hialuronidasa',
        descripcion: 'Enzima para disolver ácido hialurónico en casos de resultado indeseado, migración del producto, sobrecorrección, nódulos o complicaciones como isquemias. Indicación estrictamente clínica según tipo de relleno, tiempo de evolución, zona anatómica, grado de compromiso y objetivo del procedimiento.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 150000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: 'Única o múltiples según necesidad',
        protocolo: 'Control a los 10-14 días para evaluar corrección. Casos complejos pueden requerir repetir dosis.',
        requiereEvaluacion: true,
        evaluacionGratuita: false,
        notas: 'Precio variable según tipo de corrección (estética/urgencia), nódulos, isquemia, cantidad de unidades y complejidad anatómica.'
    },
    {
        id: 'retiro-acrocordones-laser',
        categoria: 'Facial',
        subcategoria: 'Láser',
        nombre: 'Retiro de Acrocordones con Láser CO₂',
        descripcion: 'Procedimiento dermatológico con láser CO₂ para eliminar acrocordones (fibromas blandos o skin tags) de manera precisa, rápida y con mínimo sangrado. Vaporiza la lesión con alta exactitud protegiendo piel circundante. Ideal para múltiples lesiones en cuello, axilas, párpados, tórax o áreas de roce. Seguro, ambulatorio y bajo tiempo de recuperación.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 150000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '1 sesión',
        protocolo: 'Generalmente 1 sesión para resultados deseados.',
        requiereEvaluacion: true,
        evaluacionGratuita: false,
        notas: 'Precio puede aumentar según cantidad, tamaño, localización y complejidad de zona (párpados, cuello, axilas).'
    },
    {
        id: 'laser-lentigos-pecas',
        categoria: 'Facial',
        subcategoria: 'Láser',
        nombre: 'Tratamiento Láser para Léntigos Solares y Pecas',
        descripcion: 'Léntigos solares (manchas UV) y pecas (efélides) responden muy bien al láser con tecnología adecuada según profundidad del pigmento, fototipo y zona anatómica. Plataformas de última generación para eliminar selectivamente el pigmento sin dañar piel circundante. Mejoría visible en pocas sesiones.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: null,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '1-6 sesiones cada 3-6 semanas',
        protocolo: 'Uso estricto de fotoprotección posterior indispensable.',
        requiereEvaluacion: true,
        evaluacionGratuita: false,
        notas: 'Presupuesto requiere evaluación. Precio según cantidad, tamaño, profundidad, zona y tecnología.'
    },
    {
        id: 'blefaroplastia-laser',
        categoria: 'Facial',
        subcategoria: 'Láser',
        nombre: 'Blefaroplastía No Quirúrgica con Láser CO₂',
        descripcion: 'Láser CO₂ fraccionado para tensar piel del párpado superior e inferior, disminuir laxitud, suavizar líneas finas y mejorar calidad dérmica del contorno ocular sin cirugía. Produce microzonas de ablación que estimulan neoformación de colágeno y contracción inmediata. Tecnología TetraPro y CO₂RE con profundidad, densidad y energía personalizables.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: null,
        valorHasta: null,
        duracion: '30-60 min',
        sesiones: '1-2 sesiones cada 6-12 semanas',
        protocolo: 'Resultado progresivo con mejoría continua por meses. Mantención anual opcional.',
        requiereEvaluacion: true,
        evaluacionGratuita: false,
        notas: 'Precio según severidad de laxitud, zona(s) a tratar, láser a utilizar, profundidad y sesiones necesarias.'
    },
    {
        id: 'mesoterapia-vitaminas',
        categoria: 'Facial',
        subcategoria: 'Bioestimulación',
        nombre: 'Mesoterapia con Vitaminas',
        descripcion: 'Tratamiento de bioestimulación cutánea con complejos vitamínicos, minerales, aminoácidos, antioxidantes y factores regenerativos para mejorar luminosidad, hidratación, textura y función dérmica. Cóctel de vitaminas adaptado al tipo de piel y necesidades específicas (antioxidación, hidratación, regeneración, control sebáceo).',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 120000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '3-5 sesiones cada 2-4 semanas',
        protocolo: 'Mantención cada 2-3 meses para sostener luminosidad y función dérmica.',
        requiereEvaluacion: true,
        evaluacionGratuita: false,
        notas: 'Precio según tipo/concentración de vitaminas, técnica (inyección, Dermapen, CO₂, RF), zonas y objetivo clínico.'
    },
    {
        id: 'laser-telangiectasias',
        categoria: 'Facial',
        subcategoria: 'Láser',
        nombre: 'Tratamiento de Telangiectasias con Láser',
        descripcion: 'Telangiectasias (pequeños vasos sanguíneos dilatados visibles en rostro, nariz, mejillas o piernas) requieren manejo específico según profundidad, calibre, color y distribución. Tecnologías láser avanzadas con longitud de onda ideal para cerrar vasos de forma precisa y segura, minimizando daño a piel circundante.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: null,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '1-6 sesiones cada 3-4 semanas',
        protocolo: 'Según respuesta vascular y tamaño de vasos. Mantenimiento anual en algunos casos.',
        requiereEvaluacion: true,
        evaluacionGratuita: false,
        notas: 'Presupuesto requiere evaluación. Precio según cantidad, zona, profundidad, calibre, tecnología láser y sesiones.'
    },
    {
        id: 'hifu-ultraformer',
        categoria: 'Facial',
        subcategoria: 'HIFU',
        nombre: 'HIFU Ultraformer III',
        descripcion: 'Ultrasonido micro y macrofocalizado (HIFU) más reconocido para lifting no quirúrgico. Genera puntos de calor controlado a distintas profundidades incluyendo capa SMAS (misma del lifting quirúrgico), estimulando contracción inmediata y producción progresiva de colágeno. Trata flacidez, redefine contorno mandibular, eleva pómulos, mejora papada. Protocolo personalizado por equipo dermatofuncional.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 190000,
        valorHasta: null,
        duracion: '30-60 min',
        sesiones: '1 sesión cada 6-12 meses',
        protocolo: 'Refuerzo a 3-4 meses en casos avanzados. Combinable con Sculptra, Radiesse o Morpheus8.',
        requiereEvaluacion: true,
        evaluacionGratuita: false,
        notas: 'Precio según zona (rostro, papada, cuello, corporal), cartuchos, disparos y grado de flacidez.'
    },
    {
        id: 'cicatrices-faciales',
        categoria: 'Facial',
        subcategoria: 'Láser',
        nombre: 'Tratamiento de Cicatrices Faciales',
        descripcion: 'Procedimiento avanzado para mejorar apariencia, textura, profundidad y coloración de cicatrices atróficas, hipertróficas, postacné, quirúrgicas o traumáticas. Análisis clínico detallado: tipo, tiempo de evolución, fototipo, profundidad, fibrosis, vascularización. Múltiples tecnologías: CO₂, subcisión, ResurFX, exosomas. Plan completamente personalizado.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: null,
        valorHasta: null,
        duracion: '30-60 min',
        sesiones: '3-6 sesiones cada 4-8 semanas',
        protocolo: 'Resultados progresivos asociados a remodelación de colágeno y tipo de cicatriz.',
        requiereEvaluacion: true,
        evaluacionGratuita: false,
        notas: 'Precio según tipo de cicatriz, extensión, profundidad, plan de tratamiento y número de sesiones.'
    },
    {
        id: 'relleno-peribucal-ah',
        categoria: 'Facial',
        subcategoria: 'Ácido Hialurónico',
        nombre: 'Relleno Arrugas Peribucales / Código de Barras con AH',
        descripcion: 'Ácido hialurónico de baja reticulación para integrarse naturalmente sin aportar volumen indeseado. Mejora textura, suaviza líneas y restaura elasticidad perioral manteniendo anatomía y expresión natural. Complementable con láser CO₂ superficial, polinucleótidos o exosomas para daño más profundo.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 240000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '1 sesión + control a las 2-3 semanas',
        protocolo: 'Mantención cada 8-12 meses. Arrugas profundas pueden requerir combinar con láser CO₂ superficial.',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'xantelasmas-laser',
        categoria: 'Facial',
        subcategoria: 'Láser',
        nombre: 'Eliminación de Xantelasmas con Láser CO₂',
        descripcion: 'Láser CO₂ fraccionado o quirúrgico suave para vaporizar la lesión con precisión extrema, minimizando daño térmico y reduciendo riesgo de cicatriz visible. Resultado estético superior a métodos tradicionales con recuperación más rápida y controlada. Protocolo ajustado según grosor, extensión, profundidad y ubicación (párpado superior/inferior).',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: null,
        valorHasta: null,
        duracion: '30-60 min',
        sesiones: '1-2 sesiones separadas por 6-8 semanas',
        protocolo: 'Control a los 7-10 días para seguimiento de cicatrización. Lesiones profundas pueden requerir 2 sesiones.',
        requiereEvaluacion: true,
        evaluacionGratuita: false,
        notas: 'Precio según tamaño, número de lesiones, profundidad, extensión y tecnología CO₂ utilizada.'
    },
    {
        id: 'toxina-botulinica-1-zona',
        categoria: 'Facial',
        subcategoria: 'Toxina Botulínica',
        nombre: 'Toxina Botulínica 1 Zona (Botox 1 Zona)',
        descripcion: 'Procedimiento inyectable con toxina botulínica tipo A dirigido a relajar un grupo muscular específico del rostro. Una "zona" corresponde a un área facial donde se trata un patrón muscular definido (ej.: frente, entrecejo, patitas de gallo, mentón, bunny lines, DAO, etc.). Reduce arrugas dinámicas y previene la formación de líneas estáticas. Ideal para pacientes que desean un ajuste focal, un tratamiento preventivo o mantener correcciones previas sin realizar un full face.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Medicina Estética Facial',
        valorDesde: 130000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: 'Cada 4 a 6 meses según necesidad',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    // ==================== KEREN MATUS - Kinesiología Dermatofuncional ====================
    {
        id: 'exilis-facial',
        categoria: 'Facial',
        subcategoria: 'Aparatología',
        nombre: 'Exilis Facial',
        descripcion: 'Tratamiento estético no invasivo que combina radiofrecuencia y ultrasonido para calentar de forma controlada las capas profundas de la piel, estimulando colágeno y elastina. Rejuvenece la piel, mejora flacidez leve a moderada, define contorno facial, reduce arrugas finas. Piel más firme, tensa y luminosa. Ideal 30-65 años, apto para todo tipo de piel.',
        profesional: 'Keren Hapuc Matus Islas',
        especialidad: 'Kinesióloga Dermatofuncional',
        valorDesde: 420000,
        valorHasta: 480000,
        duracion: '30-60 min',
        sesiones: '6-8 sesiones (1 vez por semana)',
        protocolo: 'Según evaluación. Sin dolor, sin tiempo de recuperación.',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'exilis-corporal',
        categoria: 'Corporal',
        subcategoria: 'Aparatología',
        nombre: 'Exilis Corporal',
        descripcion: 'Tratamiento estético no invasivo que combina radiofrecuencia y ultrasonido para calentar de forma controlada las capas profundas de la piel. Reduce grasa localizada, mejora flacidez, reafirma piel y remodela contorno corporal. Resultados visibles sin cirugía ni tiempo de recuperación. Mayores de 18 años con flacidez leve/moderada y adiposidad localizada.',
        profesional: 'Keren Hapuc Matus Islas',
        especialidad: 'Kinesióloga Dermatofuncional',
        valorDesde: 420000,
        valorHasta: 480000,
        duracion: '60 min',
        sesiones: '6-8 sesiones (1 vez por semana)',
        protocolo: 'Según evaluación. Sin dolor, sin tiempo de recuperación.',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'morpheus8-corporal-keren',
        categoria: 'Corporal',
        subcategoria: 'Radiofrecuencia',
        nombre: 'Morpheus 8 Corporal',
        descripcion: 'Remodelación profunda combinando microagujas fraccionadas con radiofrecuencia térmica. Estimula colágeno, elastina y ácido hialurónico en planos profundos. Reafirma y tensa piel flácida (abdomen, brazos, muslos, glúteos, rodillas). Mejora piel post embarazo/pérdida de peso. Disminuye estrías, cicatrices corporales y fibrosis. Lifting corporal no quirúrgico.',
        profesional: 'Keren Hapuc Matus Islas',
        especialidad: 'Kinesióloga Dermatofuncional',
        valorDesde: 700000,
        valorHasta: 900000,
        duracion: '120 min',
        sesiones: '4 sesiones (1 vez al mes)',
        protocolo: 'Según evaluación. Ideal para flacidez leve a moderada y resultados avanzados sin cirugía.',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'embody-corporal-keren',
        categoria: 'Corporal',
        subcategoria: 'Tonificación',
        nombre: 'EmBody Corporal',
        descripcion: 'Tecnología de electromagnetismo focalizado de alta intensidad (HIFEM) que provoca contracciones musculares supramáximas. Genera hipertrofia (aumento muscular) e hiperplasia (nuevas fibras). Tonifica, levanta glúteos (butt lifting), reafirma abdomen, mejora core y postura. Reduce grasa indirectamente al aumentar masa muscular. Complementa Exilis, Scizer o Clatuu.',
        profesional: 'Keren Hapuc Matus Islas',
        especialidad: 'Kinesióloga Dermatofuncional',
        valorDesde: 500000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '8-10 sesiones (2 por semana)',
        protocolo: 'Precio: $500.000 por 10 sesiones. Ideal post parto, sedentarios, fitness, levantamiento glúteos sin cirugía.',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'depilacion-laser-keren',
        categoria: 'Corporal',
        subcategoria: 'Depilación',
        nombre: 'Depilación Láser Soprano Alma',
        descripcion: 'Sistema de depilación definitiva con láser en movimiento (SHR) que calienta el folículo progresivamente, segura y prácticamente indolora. Trata todo tipo de piel, incluso bronceadas. Elimina/reduce vello de forma duradera, previene vellos encarnados y foliculitis, mejora suavidad y textura de la piel. Para piernas, axilas, bikini, espalda, brazos, rostro.',
        profesional: 'Keren Hapuc Matus Islas',
        especialidad: 'Kinesióloga Dermatofuncional',
        valorDesde: 60000,
        valorHasta: 780000,
        duracion: '30-120 min',
        sesiones: '6-8 sesiones (1 vez al mes)',
        protocolo: 'Según zona a tratar. Seguro en todo tipo de piel, incluso oscuras.',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'hydrafacial',
        categoria: 'Facial',
        subcategoria: 'Limpieza Facial',
        nombre: 'Hydrafacial',
        descripcion: 'Tratamiento facial avanzado y no invasivo: limpieza profunda, exfoliación, extracción indolora, hidratación intensiva y entrega de antioxidantes y péptidos. Tecnología Vortex-Fusion que remueve impurezas e infunde sueros concentrados. Piel luminosa, suave y revitalizada desde la primera sesión. Efecto "glow" inmediato. Para todo tipo de piel.',
        profesional: 'Dr. Nicolás Laucirica / Keren Matus / María Jesús Contreras',
        especialidad: 'Estética Facial / Kinesiología Dermatofuncional / Aparatología',
        valorDesde: 75000,
        valorHasta: null,
        duracion: '30-60 min',
        sesiones: '1 sesión al mes',
        protocolo: 'Limpieza profunda, reducción puntos negros, mejora hidratación, brillo y textura. Prepara piel para otros tratamientos.',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'hifu-facial-keren',
        categoria: 'Facial',
        subcategoria: 'HIFU',
        nombre: 'HIFU Facial',
        descripcion: 'Ultrasonido Focalizado de Alta Intensidad que estimula producción profunda de colágeno en capas internas incluyendo SMAS (misma capa del lifting quirúrgico). Microcoagulación térmica controlada que tensa, eleva y reafirma sin cirugía. Eleva mejillas, cejas, mejora papada y línea mandibular. Efecto lifting progresivo y natural.',
        profesional: 'Keren Hapuc Matus Islas',
        especialidad: 'Kinesióloga Dermatofuncional',
        valorDesde: null,
        valorHasta: null,
        duracion: '60-90 min',
        sesiones: '1 sesión al año',
        protocolo: 'Ideal desde 30-35 años. Para flacidez leve a moderada. Resultados duraderos, todo tipo de piel.',
        requiereEvaluacion: true,
        evaluacionGratuita: false,
        notas: 'Precio variable según zonas y protocolo.'
    },
    {
        id: 'postquirurgicos-keren',
        categoria: 'Corporal',
        subcategoria: 'Rehabilitación',
        nombre: 'Tratamiento Postquirúrgico',
        descripcion: 'Técnicas especializadas de manejo posoperatorio: drenaje linfático, radiofrecuencia, ultrasonido, manejo de fibrosis, tratamiento de edemas, cuidado de cicatrices. Acelera y optimiza recuperación tras cirugía estética o reconstructiva. Para liposucción, lipoescultura HD, abdominoplastía, mamoplastía, rinoplastía, lifting facial/cuello. Evita asimetrías por fibrosis.',
        profesional: 'Keren Hapuc Matus Islas',
        especialidad: 'Kinesióloga Dermatofuncional - Rehabilitación Post Quirúrgica',
        valorDesde: null,
        valorHasta: null,
        duracion: '60 min',
        sesiones: '10-20 sesiones (2 veces por semana)',
        protocolo: 'Reduce inflamación, dolor, fibrosis, adherencias, durezas. Mejora movilidad, cicatrización y resultados quirúrgicos.',
        requiereEvaluacion: true,
        evaluacionGratuita: false,
        notas: 'Precio variable según tipo de cirugía y cantidad de sesiones requeridas.'
    },
    {
        id: 'toxina-tercio-superior-facial',
        categoria: 'Facial',
        subcategoria: 'Toxina Botulínica',
        nombre: 'Toxina Botulínica en Tercio Superior Facial',
        descripcion: 'Procedimiento inyectable que utiliza toxina botulínica tipo A para relajar temporalmente los músculos responsables de arrugas dinámicas del tercio superior (frente, glabela/entrecejo y líneas perioculares). Reduce líneas de expresión, suaviza la apariencia del rostro y previene el envejecimiento prematuro. Dirigido a mujeres y hombres que buscan un resultado natural, preventivo o correctivo, con seguridad y respaldo científico.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Medicina Estética Facial',
        valorDesde: 210000,
        valorHasta: null,
        valorFidelizacion: 189000,
        duracion: '20 min',
        sesiones: 'Cada 4-6 meses. Control a los 10-14 días.',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },

    // ==================== CORPORAL - MARÍA JESÚS CONTRERAS ====================
    {
        id: 'depilacion-laser',
        categoria: 'Corporal',
        subcategoria: 'Depilación Láser',
        nombre: 'Depilación Láser Soprano Titanium',
        descripcion: 'Depilación definitiva con tecnología Soprano Titanium de Alma Lasers, el estándar de oro en depilación láser. Combina tres longitudes de onda (Alejandrita, Diodo y Nd:YAG) para tratar todos los tipos de piel y vello. Tecnología SHR (Super Hair Removal) prácticamente indolora. Apto para todo el año y todo tipo de piel, incluyendo pieles bronceadas.',
        profesional: 'María Jesús Contreras Merino',
        especialidad: 'Enfermera - Aparatología Estética',
        valorDesde: 25000,
        valorHasta: 350000,
        duracion: 'Según zona',
        sesiones: '6-10 sesiones',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'clatuu-alpha',
        categoria: 'Corporal',
        subcategoria: 'Criolipólisis',
        nombre: 'Clatuu Alpha - Criolipólisis',
        descripcion: 'Criolipólisis avanzada que utiliza enfriamiento controlado para congelar y destruir células grasas de manera segura y no invasiva. Adipocitos eliminados naturalmente por el cuerpo. Reduce grasa localizada resistente hasta 25% por sesión. Para abdomen, flancos, espalda, brazos, muslos, papada. Reducción permanente sin cirugía, sin agujas, sin reposo.',
        profesional: 'María Jesús Contreras / Keren Matus',
        especialidad: 'Aparatología Estética / Kinesiología Dermatofuncional',
        valorDesde: 180000,
        valorHasta: 1800000,
        duracion: '45 min - 6 hrs (según zonas)',
        sesiones: '1-3 sesiones según evaluación',
        protocolo: 'Ideal para grasa localizada moderada a marcada. Post parto con adiposidad persistente.',
        requiereEvaluacion: true,
        evaluacionGratuita: true,
        notas: 'Precio según cantidad de zonas y cabezales necesarios.'
    },
    {
        id: 'scizer',
        categoria: 'Corporal',
        subcategoria: 'Reducción de Grasa',
        nombre: 'Scizer HIFU Corporal',
        descripcion: 'Reducción de grasa localizada mediante ultrasonido focalizado de alta intensidad (HIFU). El Scizer destruye células grasas de forma selectiva mediante calentamiento profundo, sin dañar tejidos circundantes. Ideal para adiposidad rebelde en abdomen, flancos, muslos y brazos. Resultados visibles desde la primera sesión, con efecto máximo a los 2-3 meses.',
        profesional: 'María Jesús Contreras Merino',
        especialidad: 'Enfermera - Aparatología Estética',
        valorDesde: 200000,
        valorHasta: null,
        duracion: '45-60 min',
        sesiones: '1-2 sesiones por zona',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'hifu-corporal',
        categoria: 'Corporal',
        subcategoria: 'Lifting Corporal',
        nombre: 'HIFU Ultraformer III Corporal',
        descripcion: 'Lifting corporal sin cirugía con ultrasonido focalizado Ultraformer III. Produce contracción del colágeno y estimula su producción, logrando tensado y reafirmación de la piel. Ideal para flacidez en abdomen, brazos, muslos y glúteos. Resultados progresivos que mejoran durante 3-6 meses. El tratamiento más efectivo para flacidez corporal sin cirugía.',
        profesional: 'María Jesús Contreras Merino',
        especialidad: 'Enfermera - Aparatología Estética',
        valorDesde: 250000,
        valorHasta: 600000,
        duracion: '45-90 min',
        sesiones: '1-2 sesiones anuales',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'morpheus8-corporal',
        categoria: 'Corporal',
        subcategoria: 'Radiofrecuencia',
        nombre: 'Morpheus8 Corporal',
        descripcion: 'Tratamiento de remodelación corporal que combina microagujas con radiofrecuencia fraccionada. Penetra hasta 8mm de profundidad para tratar flacidez, estrías, celulitis y remodelar contornos. Estimula la producción de colágeno y elastina desde las capas profundas. Ideal para abdomen post-embarazo, brazos flácidos, muslos y cualquier zona con pérdida de firmeza.',
        profesional: 'María Jesús Contreras Merino',
        especialidad: 'Enfermera - Aparatología Estética',
        valorDesde: 300000,
        valorHasta: 600000,
        duracion: '45-60 min',
        sesiones: '3-4 sesiones',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'exilis-ultra',
        categoria: 'Corporal',
        subcategoria: 'Radiofrecuencia',
        nombre: 'Exilis Ultra 360',
        descripcion: 'Radiofrecuencia monopolar con ultrasonido integrado para reducción de grasa y tensado de piel simultáneo. El Exilis Ultra 360 calienta de forma controlada las capas profundas, destruyendo células grasas y estimulando colágeno. Tratamiento confortable, sin dolor ni tiempo de recuperación. Ideal para definir contornos faciales y corporales.',
        profesional: 'María Jesús Contreras Merino',
        especialidad: 'Enfermera - Aparatología Estética',
        valorDesde: 150000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: '4-6 sesiones',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'embody',
        categoria: 'Corporal',
        subcategoria: 'Tonificación',
        nombre: 'Embody - Tonificación Muscular',
        descripcion: 'Tonificación y fortalecimiento muscular mediante estimulación electromagnética de alta intensidad. Genera contracciones musculares supramáximas equivalentes a miles de abdominales o sentadillas en 30 minutos. Aumenta masa muscular, define contornos y mejora el tono. Ideal para abdomen, glúteos, muslos, brazos y pantorrillas. Complemento perfecto para el ejercicio.',
        profesional: 'María Jesús Contreras Merino',
        especialidad: 'Enfermera - Aparatología Estética',
        valorDesde: 80000,
        valorHasta: 150000,
        duracion: '30 min',
        sesiones: '8-12 sesiones',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },

    // ==================== CAPILAR - DRA. JAVIERA ARAYA ====================
    {
        id: 'consulta-tricologia',
        categoria: 'Capilar',
        subcategoria: 'Consulta',
        nombre: 'Consulta Tricológica',
        descripcion: 'Evaluación completa de la salud capilar con tricoscopia digital (visualización aumentada del cuero cabelludo y folículos). Incluye anamnesis detallada, análisis del patrón de caída, densidad capilar y calidad del cabello. Se determinan las causas de la alopecia y se diseña un plan de tratamiento personalizado. Solicitud de exámenes si es necesario.',
        profesional: 'Dra. Javiera Araya Medina',
        especialidad: 'Tricóloga - Cirugía Capilar',
        valorDesde: 40000,
        valorHasta: null,
        duracion: '40 min',
        sesiones: 'Primera consulta',
        requiereEvaluacion: false,
        evaluacionGratuita: false
    },
    {
        id: 'mesoterapia-dutasteride',
        categoria: 'Capilar',
        subcategoria: 'Mesoterapia',
        nombre: 'Mesoterapia Dutasteride',
        descripcion: 'Tratamiento inyectable con Dutasteride directamente en el cuero cabelludo para alopecia androgenética. Bloquea localmente la enzima 5-alfa reductasa responsable de la miniaturización folicular, sin los efectos sistémicos del medicamento oral. Mayor concentración en zona target. Ideal para hombres y mujeres con pérdida de cabello de patrón hereditario.',
        profesional: 'Dra. Javiera Araya Medina',
        especialidad: 'Tricóloga - Cirugía Capilar',
        valorDesde: 80000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: 'Mensual',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'mesoterapia-prp-capilar',
        categoria: 'Capilar',
        subcategoria: 'Mesoterapia',
        nombre: 'Mesoterapia PRP Capilar',
        descripcion: 'Tratamiento con Plasma Rico en Plaquetas obtenido de la propia sangre del paciente. Las plaquetas liberan factores de crecimiento que estimulan los folículos pilosos, mejoran la microcirculación y prolongan la fase de crecimiento del cabello. 100% biocompatible. Ideal combinado con otros tratamientos capilares para potenciar resultados.',
        profesional: 'Dra. Javiera Araya Medina',
        especialidad: 'Tricóloga - Cirugía Capilar',
        valorDesde: 150000,
        valorHasta: null,
        duracion: '45 min',
        sesiones: 'Mensual por 4-6 meses',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'regenera',
        categoria: 'Capilar',
        subcategoria: 'Premium',
        nombre: 'REGENERA - Células Madre Capilares',
        descripcion: 'Tratamiento de última generación con células madre autólogas (propias del paciente). Se extraen microinjertos del cuero cabelludo que contienen células madre y progenitoras capilares, se procesan y se infiltran en zonas de alopecia. ÚNICO EN CHILE exclusivo en Clínica Cialo. Regenera folículos debilitados y mejora significativamente la densidad capilar.',
        profesional: 'Dra. Javiera Araya Medina',
        especialidad: 'Tricóloga - Cirugía Capilar',
        valorDesde: 1450000,
        valorHasta: null,
        duracion: '90 min',
        sesiones: '1 sesión (duración 2+ años)',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'implante-capilar',
        categoria: 'Capilar',
        subcategoria: 'Cirugía',
        nombre: 'Implante/Injerto Capilar',
        descripcion: 'Trasplante capilar mediante técnica FUE (Follicular Unit Extraction). Se extraen unidades foliculares individuales de la zona donante (nuca) y se implantan en zonas con alopecia. Procedimiento ambulatorio bajo anestesia local. Resultados permanentes y naturales. Incluye PRP intraoperatorio para mejor prendimiento. Seguimiento completo post-operatorio.',
        profesional: 'Dra. Javiera Araya Medina',
        especialidad: 'Tricóloga - Cirugía Capilar',
        valorDesde: 2500000,
        valorHasta: 5000000,
        duracion: '4-8 horas',
        sesiones: '1 cirugía',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },

    // ==================== UROLOGÍA - DR. CONTRERAS / DR. ULLOA ====================
    {
        id: 'bioplastia-pene',
        categoria: 'Urología',
        subcategoria: 'Estética Íntima',
        nombre: 'Bioplastía de Engrosamiento Peniano',
        descripcion: 'Procedimiento de aumento del grosor peniano mediante infiltración de ácido hialurónico de alta densidad o matriz dérmica. Aumenta la circunferencia del pene de forma segura y reversible. Procedimiento ambulatorio bajo anestesia local. Resultados inmediatos con duración de 12-18 meses. Realizado por urólogos especialistas.',
        profesional: 'Dr. Guillermo Contreras / Dr. Frank Ulloa',
        especialidad: 'Urólogos',
        valorDesde: 500000,
        valorHasta: 800000,
        duracion: '60-90 min',
        sesiones: '1 procedimiento',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'circuncision',
        categoria: 'Urología',
        subcategoria: 'Cirugía',
        nombre: 'Circuncisión',
        descripcion: 'Cirugía ambulatoria para remoción del prepucio, indicada en casos de fimosis (imposibilidad de retraer el prepucio), parafimosis, infecciones recurrentes o por elección personal. Se realiza bajo anestesia local con técnica que minimiza cicatrices. Recuperación de 7-10 días. Incluye controles post-operatorios.',
        profesional: 'Dr. Guillermo Contreras',
        especialidad: 'Urólogo',
        valorDesde: 450000,
        valorHasta: null,
        duracion: '45-60 min',
        sesiones: '1 cirugía',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'vasectomia',
        categoria: 'Urología',
        subcategoria: 'Cirugía',
        nombre: 'Vasectomía',
        descripcion: 'Método anticonceptivo permanente masculino mediante la sección de los conductos deferentes. Procedimiento ambulatorio, rápido y seguro bajo anestesia local. No afecta la función sexual ni los niveles hormonales. Recuperación de 2-3 días. Se requiere espermiograma de control a los 3 meses para confirmar efectividad.',
        profesional: 'Dr. Guillermo Contreras',
        especialidad: 'Urólogo',
        valorDesde: 400000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: '1 cirugía',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'frenuloplastia',
        categoria: 'Urología',
        subcategoria: 'Cirugía',
        nombre: 'Frenuloplastía',
        descripcion: 'Corrección quirúrgica del frenillo corto (frenillo breve), condición que puede causar dolor o molestias durante las relaciones sexuales y dificultar la retracción del prepucio. Procedimiento ambulatorio bajo anestesia local. Técnica que alarga el frenillo preservando la sensibilidad. Recuperación rápida de 5-7 días.',
        profesional: 'Dr. Guillermo Contreras',
        especialidad: 'Urólogo',
        valorDesde: 350000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '1 cirugía',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },

    // ==================== GINECOESTÉTICA - STEFANIA KUNCAR ====================
    {
        id: 'rejuvenecimiento-vaginal-laser',
        categoria: 'Ginecoestética',
        subcategoria: 'Láser',
        nombre: 'Rejuvenecimiento Vaginal Láser CO2',
        descripcion: 'Tratamiento con láser CO2 fraccionado para rejuvenecimiento del canal vaginal. Estimula la producción de colágeno, mejora la elasticidad, lubricación natural y tono de los tejidos. Indicado para sequedad vaginal, síndrome genitourinario de la menopausia, laxitud vaginal post-parto e incontinencia urinaria leve. Procedimiento ambulatorio, sin dolor ni tiempo de recuperación.',
        profesional: 'Stefania Kuncar Ferrón',
        especialidad: 'Matrona - Ginecoestética',
        valorDesde: 250000,
        valorHasta: 350000,
        duracion: '30-45 min',
        sesiones: '3 sesiones',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'insercion-diu',
        categoria: 'Ginecoestética',
        subcategoria: 'Anticoncepción',
        nombre: 'Inserción DIU',
        descripcion: 'Colocación de dispositivo intrauterino (DIU) como método anticonceptivo de larga duración. Disponibles opciones hormonales (Mirena, Kyleena) y no hormonales (T de Cobre). Procedimiento rápido realizado en consulta. Efectividad superior al 99%. El DIU es reversible y puede retirarse cuando la paciente lo decida. Incluye ecografía de control.',
        profesional: 'Stefania Kuncar Ferrón',
        especialidad: 'Matrona - Ginecoestética',
        valorDesde: 40000,
        valorHasta: 60000,
        duracion: '20-30 min',
        sesiones: '1 procedimiento',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'insercion-implante',
        categoria: 'Ginecoestética',
        subcategoria: 'Anticoncepción',
        nombre: 'Inserción Implante Anticonceptivo',
        descripcion: 'Colocación de implante subdérmico anticonceptivo (Implanon/Nexplanon) en la cara interna del brazo. Método anticonceptivo de larga duración (3 años), altamente efectivo (99.9%) y reversible. Procedimiento ambulatorio bajo anestesia local. Ideal para mujeres que buscan anticoncepción sin preocupaciones diarias.',
        profesional: 'Stefania Kuncar Ferrón',
        especialidad: 'Matrona - Ginecoestética',
        valorDesde: 50000,
        valorHasta: null,
        duracion: '15-20 min',
        sesiones: '1 procedimiento',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    // ==================== CIRUGÍA MAXILOFACIAL - DR. LUIS PÉREZ ====================
    {
        id: 'bichectomia',
        categoria: 'Cirugía Maxilofacial',
        subcategoria: 'Cirugía',
        nombre: 'Bichectomía',
        descripcion: 'Extracción quirúrgica de las bolsas de Bichat, acumulaciones de grasa en las mejillas que dan un aspecto redondeado al rostro. Se realiza por vía intraoral (sin cicatrices visibles) bajo anestesia local. Afina el rostro, marca los pómulos y define el contorno facial. Resultados definitivos visibles a los 2-3 meses cuando baja la inflamación.',
        profesional: 'Dr. Luis Pérez Lagos',
        especialidad: 'Cirujano Maxilofacial',
        valorDesde: 600000,
        valorHasta: null,
        duracion: '45-60 min',
        sesiones: '1 cirugía',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'blefaroplastia-quirurgica',
        categoria: 'Cirugía Maxilofacial',
        subcategoria: 'Cirugía',
        nombre: 'Blefaroplastía Quirúrgica',
        descripcion: 'Cirugía de rejuvenecimiento de párpados que elimina el exceso de piel, grasa y músculo que causa aspecto cansado, párpados caídos o bolsas. Puede ser superior (párpado de arriba), inferior (bolsas bajo los ojos) o completa. Cicatrices ocultas en pliegues naturales. Resultados duraderos que rejuvenecen significativamente la mirada.',
        profesional: 'Dr. Luis Pérez Lagos',
        especialidad: 'Cirujano Maxilofacial',
        valorDesde: 800000,
        valorHasta: 1500000,
        duracion: '60-90 min',
        sesiones: '1 cirugía',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'otoplastia',
        categoria: 'Cirugía Maxilofacial',
        subcategoria: 'Cirugía',
        nombre: 'Otoplastía',
        descripcion: 'Corrección quirúrgica de orejas prominentes, en asa o con deformidades del cartílago. Se remodela el cartílago auricular para lograr una posición más natural y cercana a la cabeza. Cicatriz oculta detrás de la oreja. Puede realizarse desde los 6-7 años. Mejora significativamente la armonía facial y la autoestima del paciente.',
        profesional: 'Dr. Luis Pérez Lagos',
        especialidad: 'Cirujano Maxilofacial',
        valorDesde: 700000,
        valorHasta: null,
        duracion: '60-90 min',
        sesiones: '1 cirugía',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'lipo-papada',
        categoria: 'Cirugía Maxilofacial',
        subcategoria: 'Cirugía',
        nombre: 'Lipoaspiración de Papada',
        descripcion: 'Eliminación quirúrgica de la grasa submentoniana (papada) mediante lipoaspiración. Procedimiento ambulatorio bajo anestesia local que redefine el contorno del cuello y la línea mandibular. Ideal para personas con acumulación de grasa bajo el mentón resistente a dieta y ejercicio. Resultados definitivos con mínima cicatriz oculta bajo el mentón.',
        profesional: 'Dr. Luis Pérez Lagos',
        especialidad: 'Cirujano Maxilofacial',
        valorDesde: 750000,
        valorHasta: null,
        duracion: '60-90 min',
        sesiones: '1 cirugía',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'lobuloplastia',
        categoria: 'Cirugía Maxilofacial',
        subcategoria: 'Cirugía',
        nombre: 'Lobuloplastia',
        descripcion: 'Corrección quirúrgica de lóbulos de orejas dañados, rasgados o elongados por uso prolongado de aros pesados. Reconstruye el lóbulo para devolverle forma natural y permitir volver a usar aros. Procedimiento ambulatorio bajo anestesia local con resultados definitivos.',
        profesional: 'Dr. Luis Pérez Lagos',
        especialidad: 'Cirujano Maxilofacial',
        valorDesde: 400000,
        valorHasta: 700000,
        duracion: '90 min',
        sesiones: '1 cirugía',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },

    // ==================== VASCULAR - DRA. FRANCISCA GONZÁLEZ ====================
    {
        id: 'consulta-vascular',
        categoria: 'Vascular',
        subcategoria: 'Consulta',
        nombre: 'Consulta Vascular con Ecografía Doppler',
        descripcion: 'Evaluación vascular completa que incluye anamnesis, examen físico y ecografía Doppler venosa en el mismo momento. Permite diagnosticar várices, insuficiencia venosa, trombosis y otras patologías vasculares. Se determina el mejor tratamiento según hallazgos. Incluye informe ecográfico. Primera consulta indispensable antes de cualquier procedimiento vascular.',
        profesional: 'Dra. Francisca González Saldivia',
        especialidad: 'Cirujana Vascular',
        valorDesde: 50000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: 'Primera consulta',
        requiereEvaluacion: false,
        evaluacionGratuita: false
    },
    {
        id: 'escleroterapia-pequenas',
        categoria: 'Vascular',
        subcategoria: 'Escleroterapia',
        nombre: 'Escleroterapia Várices Pequeñas',
        descripcion: 'Tratamiento de arañitas vasculares y telangiectasias mediante inyección de solución esclerosante. El producto irrita la pared del vaso causando su cierre y reabsorción. Procedimiento ambulatorio, prácticamente indoloro, sin tiempo de recuperación. Requiere uso de medias de compresión post-tratamiento. Resultados visibles en semanas.',
        profesional: 'Dra. Francisca González Saldivia',
        especialidad: 'Cirujana Vascular',
        valorDesde: 80000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '2-4 sesiones',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'escleroterapia-grandes',
        categoria: 'Vascular',
        subcategoria: 'Escleroterapia',
        nombre: 'Escleroterapia Várices Grandes',
        descripcion: 'Tratamiento de várices de mayor calibre mediante escleroterapia con espuma (foam). La espuma esclerosante tiene mayor contacto con la pared venosa, siendo más efectiva para venas grandes. Guiada por ecografía para mayor precisión. Alternativa menos invasiva a la cirugía para muchos casos de insuficiencia venosa.',
        profesional: 'Dra. Francisca González Saldivia',
        especialidad: 'Cirujana Vascular',
        valorDesde: 400000,
        valorHasta: 500000,
        duracion: '45-60 min',
        sesiones: 'Según evaluación',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },

    // ==================== CAPILAR - DRA. JAVIERA ARAYA ====================
    {
        id: 'consulta-capilar',
        categoria: 'Capilar',
        subcategoria: 'Consulta',
        nombre: 'Consulta Médica Capilar',
        descripcion: 'Evaluación integral realizada por un médico especialista orientada a diagnosticar y tratar problemas del cabello y cuero cabelludo, como caída excesiva, adelgazamiento, pérdida de densidad, entradas, caspa, picazón o grasa excesiva. Se revisa historia clínica, antecedentes familiares, hábitos y se examina el cuero cabelludo con dermatoscopia si es necesario.',
        profesional: 'Dra. Javiera Araya Medina',
        especialidad: 'Tricología',
        valorDesde: 40000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: 'Primera consulta',
        requiereEvaluacion: false,
        evaluacionGratuita: false
    },
    {
        id: 'mesoterapia-capilar',
        categoria: 'Capilar',
        subcategoria: 'Mesoterapia',
        nombre: 'Mesoterapia Capilar',
        descripcion: 'Tratamiento médico capilar con microinyecciones superficiales en el cuero cabelludo, introduciendo vitaminas, aminoácidos, minerales y activos específicos para fortalecer el folículo piloso. Ayuda a disminuir la caída, mejorar calidad y grosor del cabello y estimular crecimiento en zonas de adelgazamiento.',
        profesional: 'Dra. Javiera Araya Medina',
        especialidad: 'Tricología',
        valorDesde: 110000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: 'Según plan capilar',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'prp-capilar',
        categoria: 'Capilar',
        subcategoria: 'PRP',
        nombre: 'Plasma Rico en Plaquetas Capilar',
        descripcion: 'Tratamiento que utiliza el propio plasma del paciente, rico en plaquetas y factores de crecimiento, para estimular y fortalecer los folículos pilosos. Se extrae sangre, se centrifuga y se aplica mediante microinyecciones en el cuero cabelludo. Ayuda a disminuir la caída y mejorar la densidad del cabello.',
        profesional: 'Dra. Javiera Araya Medina',
        especialidad: 'Tricología',
        valorDesde: 110000,
        valorHasta: null,
        duracion: '45-60 min',
        sesiones: 'Según plan capilar',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'injerto-capilar',
        categoria: 'Capilar',
        subcategoria: 'Injerto FUE',
        nombre: 'Injerto Capilar FUE',
        descripcion: 'Procedimiento quirúrgico que redistribuye unidades foliculares desde zona donante hacia áreas con pérdida de cabello o baja densidad. Permite recuperar cobertura capilar y mejorar línea frontal y/o coronilla. Requiere evaluación médica detallada previa.',
        profesional: 'Dra. Javiera Araya Medina',
        especialidad: 'Tricología',
        valorDesde: 1500000,
        valorHasta: null,
        duracion: '4-8 horas',
        sesiones: '1 cirugía',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'regenera-capilar',
        categoria: 'Capilar',
        subcategoria: 'Regenera',
        nombre: 'Regenera Activa',
        descripcion: 'Tratamiento capilar avanzado que utiliza células autólogas obtenidas del propio paciente. Se procesan muestras de cuero cabelludo sano para liberar células progenitoras y factores de crecimiento, que se infiltran en zonas con adelgazamiento capilar. Estimula folículos debilitados y mejora calidad del cabello.',
        profesional: 'Dra. Javiera Araya Medina',
        especialidad: 'Tricología',
        valorDesde: 1250000,
        valorHasta: null,
        duracion: '90-120 min',
        sesiones: '1 sesión',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },

    // ==================== CORPORAL - MARÍA JESÚS CONTRERAS ====================
    {
        id: 'consulta-corporal',
        categoria: 'Corporal',
        subcategoria: 'Consulta',
        nombre: 'Consulta Corporal',
        descripcion: 'Evaluación inicial orientada a pacientes que desean mejorar su figura, flacidez, celulitis o grasa localizada. Se evalúa composición corporal, zonas de preocupación, hábitos y objetivos para diseñar un plan personalizado.',
        profesional: 'María Jesús Contreras',
        especialidad: 'Remodelación Corporal',
        valorDesde: 0,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: 'Primera consulta (sin costo)',
        requiereEvaluacion: false,
        evaluacionGratuita: true
    },
    {
        id: 'depilacion-axilas-sesion',
        categoria: 'Corporal',
        subcategoria: 'Depilación Láser',
        nombre: 'Depilación Láser Axilas (1 sesión)',
        descripcion: 'Sesión individual de depilación láser en axilas con Soprano Titanium, tecnología de triple longitud de onda que permite reducción progresiva del vello de forma segura y confortable. Mejora higiene y aspecto de la piel.',
        profesional: 'María Jesús Contreras',
        especialidad: 'Depilación Láser',
        valorDesde: 22000,
        valorHasta: null,
        duracion: '15-20 min',
        sesiones: '1 sesión',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'depilacion-piernas-completas',
        categoria: 'Corporal',
        subcategoria: 'Depilación Láser',
        nombre: 'Depilación Láser Piernas Completas (1 sesión)',
        descripcion: 'Sesión de depilación láser en piernas completas (muslos hasta pies y dedos) con Soprano Titanium. Reduce dependencia de cera o rasuradora, evitando irritación, foliculitis y sombreado.',
        profesional: 'María Jesús Contreras',
        especialidad: 'Depilación Láser',
        valorDesde: 60000,
        valorHasta: null,
        duracion: '60-90 min',
        sesiones: '1 sesión',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'depilacion-cuerpo-completo',
        categoria: 'Corporal',
        subcategoria: 'Depilación Láser',
        nombre: 'Depilación Láser Cuerpo Completo (1 sesión)',
        descripcion: 'Sesión de depilación láser de cuerpo completo con Soprano Titanium, incluyendo piernas, brazos, axilas, zona íntima, abdomen, espalda y glúteos según evaluación.',
        profesional: 'María Jesús Contreras',
        especialidad: 'Depilación Láser',
        valorDesde: 100000,
        valorHasta: 130000,
        duracion: '2-3 horas',
        sesiones: '1 sesión',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'criolipolis-clatuu',
        categoria: 'Corporal',
        subcategoria: 'Criolipólisis',
        nombre: 'Criolipólisis Clatuu Alpha (1 cabezal)',
        descripcion: 'Tratamiento de criolipólisis 360° orientado a reducir grasa localizada en zonas específicas (abdomen, flancos, espalda, brazos, muslos) mediante enfriamiento controlado que actúa selectivamente sobre los adipocitos.',
        profesional: 'María Jesús Contreras',
        especialidad: 'Remodelación Corporal',
        valorDesde: 200000,
        valorHasta: null,
        duracion: '60 min por cabezal',
        sesiones: '1-2 sesiones por zona',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },

    // ==================== GINECOESTÉTICA ====================
    {
        id: 'consulta-ginecologica',
        categoria: 'Ginecoestética',
        subcategoria: 'Consulta',
        nombre: 'Consulta Ginecológica',
        descripcion: 'Consulta médica orientada a salud íntima y ginecológica de la mujer. Aborda controles de rutina, alteraciones menstruales, dolor pélvico, flujo anormal, anticoncepción, cambios postparto o postmenopausia y salud sexual.',
        profesional: 'Dra. María Laura Villarroel',
        especialidad: 'Ginecología',
        valorDesde: 40000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: 'Primera consulta',
        requiereEvaluacion: false,
        evaluacionGratuita: false
    },
    {
        id: 'laser-co2-vaginal',
        categoria: 'Ginecoestética',
        subcategoria: 'Láser CO2',
        nombre: 'Láser CO2 Íntimo Femenino',
        descripcion: 'Tratamiento con láser CO2 fraccionado para rejuvenecimiento vaginal. Mejora sequedad, laxitud, incontinencia leve y síntomas de atrofia vaginal. Estimula producción de colágeno y elastina en mucosa vaginal.',
        profesional: 'Dra. María Laura Villarroel',
        especialidad: 'Ginecología',
        valorDesde: 250000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: '1-3 sesiones',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'consulta-matrona',
        categoria: 'Ginecoestética',
        subcategoria: 'Consulta',
        nombre: 'Consulta Matrona',
        descripcion: 'Consulta orientada a salud ginecológica, íntima y sexual femenina. Aborda control ginecológico básico, molestias íntimas, sequedad vaginal, dolor en relaciones, anticoncepción e inserción de implante.',
        profesional: 'Stefania Kuncar',
        especialidad: 'Matronería',
        valorDesde: 30000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: 'Primera consulta',
        requiereEvaluacion: false,
        evaluacionGratuita: false
    },
    {
        id: 'peeling-intimo',
        categoria: 'Ginecoestética',
        subcategoria: 'Peeling',
        nombre: 'Peeling Íntimo / Blanqueamiento Zonas Íntimas',
        descripcion: 'Tratamiento con peeling químico especializado para aclarar y mejorar la apariencia de zonas íntimas como ingle, zona perianal y vulvar. Promueve renovación celular, mejora textura y uniformiza el tono de la piel. Precio por 1 zona: $130.000 | 2 zonas misma sesión: $150.000.',
        profesional: 'Stefania Kuncar',
        especialidad: 'Matronería',
        valorDesde: 130000,
        valorHasta: 150000,
        duracion: '30-45 min',
        sesiones: '4-6 sesiones (cada 15-21 días)',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },

    // ==================== UROLOGÍA ====================
    {
        id: 'consulta-urologica',
        categoria: 'Urología',
        subcategoria: 'Consulta',
        nombre: 'Consulta Urológica',
        descripcion: 'Consulta médica especializada orientada a salud íntima y funcional masculina. Evalúa agrandamiento peneano con ácido hialurónico, desempeño sexual, molestias genitales, cambios en forma o tamaño.',
        profesional: 'Dr. Guillermo Contreras',
        especialidad: 'Urología',
        valorDesde: 50000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: 'Primera consulta',
        requiereEvaluacion: false,
        evaluacionGratuita: false
    },

    // ==================== AH GLÚTEO ====================
    {
        id: 'ah-gluteo-100ml',
        categoria: 'Corporal',
        subcategoria: 'Relleno Corporal',
        nombre: 'Ácido Hialurónico Glúteo 100ml',
        descripcion: 'Tratamiento corporal mínimamente invasivo con ácido hialurónico de alta densidad para mejorar volumen, proyección y forma de los glúteos. Permite redondear, levantar visualmente y corregir asimetrías.',
        profesional: 'Dra. Elga Viviana Peña',
        especialidad: 'Medicina Estética',
        valorDesde: 600000,
        valorHasta: null,
        duracion: '60-90 min',
        sesiones: '1 sesión (duración 18-24 meses)',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'ah-gluteo-200ml',
        categoria: 'Corporal',
        subcategoria: 'Relleno Corporal',
        nombre: 'Ácido Hialurónico Glúteo 200ml',
        descripcion: 'Tratamiento corporal con ácido hialurónico de alta densidad para volumen y forma de glúteos. Mayor cantidad de producto para resultados más notorios.',
        profesional: 'Dra. Elga Viviana Peña',
        especialidad: 'Medicina Estética',
        valorDesde: 1100000,
        valorHasta: null,
        duracion: '90-120 min',
        sesiones: '1 sesión (duración 18-24 meses)',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },

    // ==================== NUTRICIÓN ====================
    {
        id: 'consulta-nutricional',
        categoria: 'Nutrición',
        subcategoria: 'Consulta',
        nombre: 'Consulta Nutricional (incluye InBody 970)',
        descripcion: 'Evaluación nutricional integral que incluye anamnesis, medición de composición corporal con InBody 970, análisis de masa muscular, grasa corporal, agua y metabolismo basal. Se entrega plan alimentario personalizado según objetivos.',
        profesional: 'Walter Zaror / Valentina Verdejo',
        especialidad: 'Nutricionistas',
        valorDesde: 40000,
        valorHasta: null,
        duracion: '45-60 min',
        sesiones: 'Primera consulta + controles mensuales',
        requiereEvaluacion: false,
        evaluacionGratuita: false
    },
    {
        id: 'examen-inbody',
        categoria: 'Nutrición',
        subcategoria: 'Exámenes',
        nombre: 'Examen InBody 970 (sin interpretación)',
        descripcion: 'Medición de composición corporal con tecnología InBody 970. Entrega datos de masa muscular, grasa corporal, agua corporal total, metabolismo basal y análisis segmental. Solo examen, sin interpretación profesional.',
        profesional: 'Walter Zaror / Valentina Verdejo',
        especialidad: 'Nutricionistas',
        valorDesde: 15000,
        valorHasta: null,
        duracion: '15 min',
        sesiones: '1 examen',
        requiereEvaluacion: false,
        evaluacionGratuita: false
    },
    {
        id: 'calorimetria-indirecta',
        categoria: 'Nutrición',
        subcategoria: 'Exámenes',
        nombre: 'Calorimetría Indirecta',
        descripcion: 'Medición del gasto energético en reposo mediante calorimetría indirecta. Determina con precisión las calorías que el cuerpo consume en reposo, permitiendo diseñar planes nutricionales más exactos.',
        profesional: 'Walter Zaror / Valentina Verdejo',
        especialidad: 'Nutricionistas',
        valorDesde: 50000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '1 examen',
        requiereEvaluacion: false,
        evaluacionGratuita: false
    }
];

// Obtener categorías únicas
function getCategoriasTratamientos() {
    const categorias = [...new Set(tratamientosData.map(t => t.categoria))];
    return categorias.sort();
}

// Obtener subcategorías por categoría
function getSubcategoriasTratamientos(categoria) {
    const subcats = [...new Set(tratamientosData.filter(t => t.categoria === categoria).map(t => t.subcategoria))];
    return subcats.sort();
}
