/**
 * Catálogo de Tratamientos de Clínica Cialo
 * Información completa de cada tratamiento: nombre, descripción, profesional, precio, duración, etc.
 */

const tratamientosData = [
    // ==================== FACIAL - DR. NICOLÁS LAUCIRICA ====================
    {
        id: 'toxina-tercio-superior',
        categoria: 'Facial',
        subcategoria: 'Toxina Botulínica',
        nombre: 'Toxina Botulínica Tercio Superior',
        descripcion: 'Tratamiento con toxina botulínica para suavizar y prevenir arrugas dinámicas del tercio superior del rostro. Actúa sobre líneas de expresión en frente, entrecejo (líneas del 11) y patas de gallo. Resultados visibles desde el día 3-5, con efecto máximo a las 2 semanas. Procedimiento rápido, mínimamente invasivo y sin tiempo de recuperación.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 150000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '1 sesión (efecto 4-6 meses)',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'toxina-bruxismo',
        categoria: 'Facial',
        subcategoria: 'Toxina Botulínica',
        nombre: 'Toxina Botulínica Bruxismo',
        descripcion: 'Aplicación de toxina botulínica en músculos maseteros para tratar el bruxismo (rechinar de dientes). Relaja la musculatura mandibular, reduce dolor y tensión facial, previene el desgaste dental y como beneficio estético, afina el ángulo mandibular logrando un rostro más ovalado. Ideal para pacientes con mandíbula cuadrada por hipertrofia maseterina.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 200000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '1 sesión (efecto 4-6 meses)',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'toxina-sonrisa-gingival',
        categoria: 'Facial',
        subcategoria: 'Toxina Botulínica',
        nombre: 'Toxina Botulínica Sonrisa Gingival',
        descripcion: 'Corrección de la sonrisa gingival mediante toxina botulínica. Modula la elevación del labio superior para reducir la exposición excesiva de encía al sonreír. Tratamiento sutil que logra una sonrisa más armónica y natural. Procedimiento rápido con resultados visibles en pocos días.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 100000,
        valorHasta: null,
        duracion: '20 min',
        sesiones: '1 sesión (efecto 4-6 meses)',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'toxina-full-face',
        categoria: 'Facial',
        subcategoria: 'Toxina Botulínica',
        nombre: 'Toxina Botulínica Full Face',
        descripcion: 'Tratamiento integral con toxina botulínica que aborda múltiples áreas del rostro: tercio superior (frente, entrecejo, patas de gallo), tercio medio y tercio inferior (líneas peribucales, mentón, cuello). Proporciona un rejuvenecimiento global natural, previniendo y suavizando arrugas de expresión en todo el rostro.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 350000,
        valorHasta: null,
        duracion: '45 min',
        sesiones: '1 sesión (efecto 4-6 meses)',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'rinomodelacion',
        categoria: 'Facial',
        subcategoria: 'Ácido Hialurónico',
        nombre: 'Rinomodelación',
        descripcion: 'Remodelación nasal sin cirugía mediante ácido hialurónico. Permite corregir imperfecciones como dorso irregular, punta caída, asimetrías o pequeñas desviaciones. Mejora el perfil nasal de forma inmediata con resultados naturales. Procedimiento ambulatorio, reversible y sin tiempo de recuperación. Alternativa ideal para quienes buscan mejorar su nariz sin someterse a rinoplastia quirúrgica.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 350000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: '1 sesión (duración 12-18 meses)',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'labios-ah',
        categoria: 'Facial',
        subcategoria: 'Ácido Hialurónico',
        nombre: 'Labios con Ácido Hialurónico',
        descripcion: 'Aumento y definición labial con ácido hialurónico de última generación. Permite dar volumen, proyección, definir el arco de cupido, corregir asimetrías e hidratar profundamente. Se personaliza según el deseo de cada paciente, desde resultados muy naturales hasta labios más voluminosos. El procedimiento incluye anestesia tópica para máximo confort.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 250000,
        valorHasta: 400000,
        duracion: '30 min',
        sesiones: '1 sesión (duración 8-12 meses)',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'menton-ah',
        categoria: 'Facial',
        subcategoria: 'Ácido Hialurónico',
        nombre: 'Mentón con Ácido Hialurónico',
        descripcion: 'Proyección y definición del mentón mediante ácido hialurónico de alta densidad. Mejora el equilibrio y armonía del perfil facial, corrige mentones retraídos o poco definidos. Ideal para lograr un perfil más balanceado sin cirugía. Resultados inmediatos, naturales y reversibles.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 300000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '1 sesión (duración 12-18 meses)',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'pomulos-ah',
        categoria: 'Facial',
        subcategoria: 'Ácido Hialurónico',
        nombre: 'Pómulos con Ácido Hialurónico',
        descripcion: 'Volumización y definición de pómulos con ácido hialurónico. Restaura el volumen perdido por el envejecimiento, proporciona efecto lifting natural al tercio medio facial y mejora la estructura ósea del rostro. Ideal para rostros que han perdido definición o para quienes desean pómulos más marcados y juveniles.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 350000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: '1 sesión (duración 12-18 meses)',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'ojeras-ah',
        categoria: 'Facial',
        subcategoria: 'Ácido Hialurónico',
        nombre: 'Ojeras / Surco Lagrimal',
        descripcion: 'Tratamiento del surco lagrimal y ojeras hundidas con ácido hialurónico específico para esta delicada zona. Mejora el aspecto cansado, reduce la sombra oscura bajo los ojos y suaviza el hundimiento. Requiere técnica especializada por ser una zona muy vascularizada. Resultados sutiles pero transformadores que devuelven frescura a la mirada.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 300000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '1 sesión (duración 12-18 meses)',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'surco-nasogeniano-ah',
        categoria: 'Facial',
        subcategoria: 'Ácido Hialurónico',
        nombre: 'Surco Nasogeniano',
        descripcion: 'Corrección de los surcos nasogenianos (líneas de la sonrisa) que van desde la nariz hasta las comisuras labiales. Mediante ácido hialurónico se suavizan estos pliegues que se profundizan con la edad, devolviendo un aspecto más juvenil y descansado al rostro. Resultados inmediatos y naturales.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 250000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '1 sesión (duración 8-12 meses)',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'definicion-mandibular',
        categoria: 'Facial',
        subcategoria: 'Ácido Hialurónico',
        nombre: 'Definición Mandibular',
        descripcion: 'Definición y contorneo de la línea mandibular con ácido hialurónico de alta densidad. Crea una mandíbula más marcada y definida, mejora el ángulo mandibular y proporciona un aspecto más juvenil y estructurado. Ideal para combatir la pérdida de definición por flacidez o para quienes desean un jawline más pronunciado.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 350000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: '1 sesión (duración 12-18 meses)',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'armonizacion-facial',
        categoria: 'Facial',
        subcategoria: 'Armonización',
        nombre: 'Armonización Facial',
        descripcion: 'Tratamiento integral que combina múltiples técnicas (ácido hialurónico, toxina botulínica, bioestimuladores) para lograr un rostro equilibrado y armónico. Se diseña un plan personalizado según las necesidades de cada paciente, abordando proporciones faciales, volúmenes, arrugas y calidad de piel. Ideal para transformaciones completas con resultados naturales.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 800000,
        valorHasta: 2500000,
        duracion: '60-90 min',
        sesiones: '1-3 sesiones según plan',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'sculptra',
        categoria: 'Facial',
        subcategoria: 'Bioestimuladores',
        nombre: 'Sculptra®',
        descripcion: 'Bioestimulador de colágeno a base de ácido poli-L-láctico. Estimula la producción natural de colágeno de forma progresiva, mejorando la calidad, densidad y firmeza de la piel. Los resultados aparecen gradualmente durante semanas/meses y pueden durar hasta 2 años. Ideal para tratamiento de flacidez facial, pérdida de volumen y rejuvenecimiento global.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 450000,
        valorHasta: null,
        duracion: '45 min',
        sesiones: '2-3 sesiones espaciadas',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'radiesse',
        categoria: 'Facial',
        subcategoria: 'Bioestimuladores',
        nombre: 'Radiesse®',
        descripcion: 'Bioestimulador de hidroxiapatita cálcica que ofrece doble acción: efecto tensor inmediato por su capacidad de relleno y bioestimulación a largo plazo estimulando la producción de colágeno propio. Ideal para zonas que requieren soporte estructural como pómulos, mentón, mandíbula y manos. Resultados duraderos de 12-18 meses.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 400000,
        valorHasta: null,
        duracion: '45 min',
        sesiones: '1-2 sesiones',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'ellanse',
        categoria: 'Facial',
        subcategoria: 'Bioestimuladores',
        nombre: 'Ellansé®',
        descripcion: 'Bioestimulador de policaprolactona (PCL) que combina relleno inmediato con bioestimulación prolongada. Disponible en diferentes duraciones (S, M, L, E) según las necesidades del paciente, con efectos que pueden durar de 1 a 4 años. Ideal para quienes buscan resultados duraderos y naturales sin necesidad de retoques frecuentes.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 500000,
        valorHasta: null,
        duracion: '45 min',
        sesiones: '1 sesión',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'adn-salmon',
        categoria: 'Facial',
        subcategoria: 'Revitalización',
        nombre: 'ADN de Salmón',
        descripcion: 'Tratamiento revitalizante con polinucleótidos extraídos de ADN de salmón. Regenera y revitaliza la piel a nivel celular, mejora la hidratación profunda, luminosidad, elasticidad y textura. Estimula la producción de colágeno y elastina. Ideal para pieles deshidratadas, apagadas o con signos iniciales de envejecimiento.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 180000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '3-4 sesiones',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'hilos-tensores',
        categoria: 'Facial',
        subcategoria: 'Hilos',
        nombre: 'Hilos Tensores y Revitalizantes',
        descripcion: 'Tratamiento de lifting sin cirugía mediante hilos de PDO (polidioxanona) o PLLA. Los hilos tensores reposicionan tejidos caídos (papada, mejillas, cejas), mientras los hilos revitalizantes estimulan colágeno mejorando la calidad de la piel. Procedimiento mínimamente invasivo con resultados inmediatos que mejoran progresivamente.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 350000,
        valorHasta: 1200000,
        duracion: '45-60 min',
        sesiones: '1 sesión',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'exosomas',
        categoria: 'Facial',
        subcategoria: 'Revitalización',
        nombre: 'Exosomas',
        descripcion: 'Tratamiento de medicina regenerativa con exosomas, vesículas extracelulares que contienen factores de crecimiento, proteínas y ARN mensajero. Activan la regeneración celular, mejoran la textura, luminosidad, hidratación y firmeza de la piel. Tecnología de vanguardia para rejuvenecimiento facial profundo y reparación de daño cutáneo.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 250000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: '3-4 sesiones',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'hydrafacial',
        categoria: 'Facial',
        subcategoria: 'Dermatofuncional',
        nombre: 'HydraFacial® MD',
        descripcion: 'Tratamiento facial premium que combina limpieza profunda, exfoliación, extracción e hidratación intensa en un solo procedimiento. Utiliza tecnología patentada de vórtex para limpiar poros, eliminar impurezas e infundir sueros activos personalizados. Resultados inmediatos: piel luminosa, hidratada y renovada. Sin tiempo de recuperación.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 120000,
        valorHasta: null,
        duracion: '45-60 min',
        sesiones: 'Mensual recomendado',
        requiereEvaluacion: false,
        evaluacionGratuita: false
    },
    {
        id: 'hollywood-peel',
        categoria: 'Facial',
        subcategoria: 'Láser',
        nombre: 'Hollywood Peel',
        descripcion: 'Tratamiento láser con carbón activado que proporciona un efecto glow instantáneo. El láser Nd:YAG calienta las partículas de carbón aplicadas sobre la piel, logrando limpieza profunda de poros, reducción de puntos negros, estimulación de colágeno y una piel más luminosa y uniforme. Llamado así porque es el favorito de las celebridades antes de eventos.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 150000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: '3-6 sesiones recomendadas',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'laser-melasma',
        categoria: 'Facial',
        subcategoria: 'Láser',
        nombre: 'Láser Melasma y Pigmentaciones',
        descripcion: 'Protocolo especializado con láser para tratamiento de manchas hormonales (melasma), manchas solares, lentigos y otras hiperpigmentaciones. Utiliza parámetros específicos para fragmentar el pigmento sin dañar la piel circundante. Requiere protocolo de mantenimiento y fotoprotección estricta. Plan de tratamiento personalizado según tipo de mancha.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 180000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: 'Según protocolo',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'blefaroplastia-laser',
        categoria: 'Facial',
        subcategoria: 'Láser',
        nombre: 'Blefaroplastía Láser',
        descripcion: 'Rejuvenecimiento de párpados mediante láser CO2 fraccionado. Trata la piel excedente, arrugas finas y flacidez palpebral sin necesidad de cirugía convencional. El láser vaporiza capas de piel de forma controlada y estimula la producción de colágeno. Resultados progresivos con recuperación más rápida que la blefaroplastía quirúrgica.',
        profesional: 'Dr. Nicolás Laucirica',
        especialidad: 'Cirujano Dentista - Estética Facial',
        valorDesde: 400000,
        valorHasta: null,
        duracion: '45-60 min',
        sesiones: '1-2 sesiones',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },

    // ==================== CORPORAL - MARÍA JESÚS CONTRERAS ====================
    {
        id: 'depilacion-laser',
        categoria: 'Corporal',
        subcategoria: 'Depilación Láser',
        nombre: 'Depilación Láser Soprano Titanium',
        descripcion: 'Depilación definitiva con tecnología Soprano Titanium de Alma Lasers, el estándar de oro en depilación láser. Combina tres longitudes de onda (Alejandrita, Diodo y Nd:YAG) para tratar todos los tipos de piel y vello. Tecnología SHR (Super Hair Removal) prácticamente indolora. Apto para todo el año y todo tipo de piel, incluyendo pieles bronceadas.',
        profesional: 'María Jesús Contreras Merino',
        especialidad: 'Enfermera - Aparatología Estética',
        valorDesde: 25000,
        valorHasta: 350000,
        duracion: 'Según zona',
        sesiones: '6-10 sesiones',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'clatuu-alpha',
        categoria: 'Corporal',
        subcategoria: 'Criolipólisis',
        nombre: 'Clatuu Alpha - Criolipólisis',
        descripcion: 'Reducción de grasa localizada mediante criolipólisis (congelamiento controlado). El equipo Clatuu Alpha congela selectivamente las células grasas que luego son eliminadas naturalmente por el cuerpo. Reduce hasta un 25% de grasa en la zona tratada por sesión. Ideal para adiposidad localizada resistente a dieta y ejercicio en abdomen, flancos, muslos, brazos y papada.',
        profesional: 'María Jesús Contreras Merino',
        especialidad: 'Enfermera - Aparatología Estética',
        valorDesde: 180000,
        valorHasta: 350000,
        duracion: '45-60 min por zona',
        sesiones: '1-3 sesiones por zona',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'scizer',
        categoria: 'Corporal',
        subcategoria: 'Reducción de Grasa',
        nombre: 'Scizer HIFU Corporal',
        descripcion: 'Reducción de grasa localizada mediante ultrasonido focalizado de alta intensidad (HIFU). El Scizer destruye células grasas de forma selectiva mediante calentamiento profundo, sin dañar tejidos circundantes. Ideal para adiposidad rebelde en abdomen, flancos, muslos y brazos. Resultados visibles desde la primera sesión, con efecto máximo a los 2-3 meses.',
        profesional: 'María Jesús Contreras Merino',
        especialidad: 'Enfermera - Aparatología Estética',
        valorDesde: 200000,
        valorHasta: null,
        duracion: '45-60 min',
        sesiones: '1-2 sesiones por zona',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'hifu-corporal',
        categoria: 'Corporal',
        subcategoria: 'Lifting Corporal',
        nombre: 'HIFU Ultraformer III Corporal',
        descripcion: 'Lifting corporal sin cirugía con ultrasonido focalizado Ultraformer III. Produce contracción del colágeno y estimula su producción, logrando tensado y reafirmación de la piel. Ideal para flacidez en abdomen, brazos, muslos y glúteos. Resultados progresivos que mejoran durante 3-6 meses. El tratamiento más efectivo para flacidez corporal sin cirugía.',
        profesional: 'María Jesús Contreras Merino',
        especialidad: 'Enfermera - Aparatología Estética',
        valorDesde: 250000,
        valorHasta: 600000,
        duracion: '45-90 min',
        sesiones: '1-2 sesiones anuales',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'morpheus8-corporal',
        categoria: 'Corporal',
        subcategoria: 'Radiofrecuencia',
        nombre: 'Morpheus8 Corporal',
        descripcion: 'Tratamiento de remodelación corporal que combina microagujas con radiofrecuencia fraccionada. Penetra hasta 8mm de profundidad para tratar flacidez, estrías, celulitis y remodelar contornos. Estimula la producción de colágeno y elastina desde las capas profundas. Ideal para abdomen post-embarazo, brazos flácidos, muslos y cualquier zona con pérdida de firmeza.',
        profesional: 'María Jesús Contreras Merino',
        especialidad: 'Enfermera - Aparatología Estética',
        valorDesde: 300000,
        valorHasta: 600000,
        duracion: '45-60 min',
        sesiones: '3-4 sesiones',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'exilis-ultra',
        categoria: 'Corporal',
        subcategoria: 'Radiofrecuencia',
        nombre: 'Exilis Ultra 360',
        descripcion: 'Radiofrecuencia monopolar con ultrasonido integrado para reducción de grasa y tensado de piel simultáneo. El Exilis Ultra 360 calienta de forma controlada las capas profundas, destruyendo células grasas y estimulando colágeno. Tratamiento confortable, sin dolor ni tiempo de recuperación. Ideal para definir contornos faciales y corporales.',
        profesional: 'María Jesús Contreras Merino',
        especialidad: 'Enfermera - Aparatología Estética',
        valorDesde: 150000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: '4-6 sesiones',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'embody',
        categoria: 'Corporal',
        subcategoria: 'Tonificación',
        nombre: 'Embody - Tonificación Muscular',
        descripcion: 'Tonificación y fortalecimiento muscular mediante estimulación electromagnética de alta intensidad. Genera contracciones musculares supramáximas equivalentes a miles de abdominales o sentadillas en 30 minutos. Aumenta masa muscular, define contornos y mejora el tono. Ideal para abdomen, glúteos, muslos, brazos y pantorrillas. Complemento perfecto para el ejercicio.',
        profesional: 'María Jesús Contreras Merino',
        especialidad: 'Enfermera - Aparatología Estética',
        valorDesde: 80000,
        valorHasta: 150000,
        duracion: '30 min',
        sesiones: '8-12 sesiones',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },

    // ==================== CAPILAR - DRA. JAVIERA ARAYA ====================
    {
        id: 'consulta-tricologia',
        categoria: 'Capilar',
        subcategoria: 'Consulta',
        nombre: 'Consulta Tricológica',
        descripcion: 'Evaluación completa de la salud capilar con tricoscopia digital (visualización aumentada del cuero cabelludo y folículos). Incluye anamnesis detallada, análisis del patrón de caída, densidad capilar y calidad del cabello. Se determinan las causas de la alopecia y se diseña un plan de tratamiento personalizado. Solicitud de exámenes si es necesario.',
        profesional: 'Dra. Javiera Araya Medina',
        especialidad: 'Tricóloga - Cirugía Capilar',
        valorDesde: 40000,
        valorHasta: null,
        duracion: '40 min',
        sesiones: 'Primera consulta',
        requiereEvaluacion: false,
        evaluacionGratuita: false
    },
    {
        id: 'mesoterapia-dutasteride',
        categoria: 'Capilar',
        subcategoria: 'Mesoterapia',
        nombre: 'Mesoterapia Dutasteride',
        descripcion: 'Tratamiento inyectable con Dutasteride directamente en el cuero cabelludo para alopecia androgenética. Bloquea localmente la enzima 5-alfa reductasa responsable de la miniaturización folicular, sin los efectos sistémicos del medicamento oral. Mayor concentración en zona target. Ideal para hombres y mujeres con pérdida de cabello de patrón hereditario.',
        profesional: 'Dra. Javiera Araya Medina',
        especialidad: 'Tricóloga - Cirugía Capilar',
        valorDesde: 80000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: 'Mensual',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'mesoterapia-prp-capilar',
        categoria: 'Capilar',
        subcategoria: 'Mesoterapia',
        nombre: 'Mesoterapia PRP Capilar',
        descripcion: 'Tratamiento con Plasma Rico en Plaquetas obtenido de la propia sangre del paciente. Las plaquetas liberan factores de crecimiento que estimulan los folículos pilosos, mejoran la microcirculación y prolongan la fase de crecimiento del cabello. 100% biocompatible. Ideal combinado con otros tratamientos capilares para potenciar resultados.',
        profesional: 'Dra. Javiera Araya Medina',
        especialidad: 'Tricóloga - Cirugía Capilar',
        valorDesde: 150000,
        valorHasta: null,
        duracion: '45 min',
        sesiones: 'Mensual por 4-6 meses',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'regenera',
        categoria: 'Capilar',
        subcategoria: 'Premium',
        nombre: 'REGENERA - Células Madre Capilares',
        descripcion: 'Tratamiento de última generación con células madre autólogas (propias del paciente). Se extraen microinjertos del cuero cabelludo que contienen células madre y progenitoras capilares, se procesan y se infiltran en zonas de alopecia. ÚNICO EN CHILE exclusivo en Clínica Cialo. Regenera folículos debilitados y mejora significativamente la densidad capilar.',
        profesional: 'Dra. Javiera Araya Medina',
        especialidad: 'Tricóloga - Cirugía Capilar',
        valorDesde: 1450000,
        valorHasta: null,
        duracion: '90 min',
        sesiones: '1 sesión (duración 2+ años)',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'implante-capilar',
        categoria: 'Capilar',
        subcategoria: 'Cirugía',
        nombre: 'Implante/Injerto Capilar',
        descripcion: 'Trasplante capilar mediante técnica FUE (Follicular Unit Extraction). Se extraen unidades foliculares individuales de la zona donante (nuca) y se implantan en zonas con alopecia. Procedimiento ambulatorio bajo anestesia local. Resultados permanentes y naturales. Incluye PRP intraoperatorio para mejor prendimiento. Seguimiento completo post-operatorio.',
        profesional: 'Dra. Javiera Araya Medina',
        especialidad: 'Tricóloga - Cirugía Capilar',
        valorDesde: 2500000,
        valorHasta: 5000000,
        duracion: '4-8 horas',
        sesiones: '1 cirugía',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },

    // ==================== UROLOGÍA - DR. CONTRERAS / DR. ULLOA ====================
    {
        id: 'bioplastia-pene',
        categoria: 'Urología',
        subcategoria: 'Estética Íntima',
        nombre: 'Bioplastía de Engrosamiento Peniano',
        descripcion: 'Procedimiento de aumento del grosor peniano mediante infiltración de ácido hialurónico de alta densidad o matriz dérmica. Aumenta la circunferencia del pene de forma segura y reversible. Procedimiento ambulatorio bajo anestesia local. Resultados inmediatos con duración de 12-18 meses. Realizado por urólogos especialistas.',
        profesional: 'Dr. Guillermo Contreras / Dr. Frank Ulloa',
        especialidad: 'Urólogos',
        valorDesde: 500000,
        valorHasta: 800000,
        duracion: '60-90 min',
        sesiones: '1 procedimiento',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'circuncision',
        categoria: 'Urología',
        subcategoria: 'Cirugía',
        nombre: 'Circuncisión',
        descripcion: 'Cirugía ambulatoria para remoción del prepucio, indicada en casos de fimosis (imposibilidad de retraer el prepucio), parafimosis, infecciones recurrentes o por elección personal. Se realiza bajo anestesia local con técnica que minimiza cicatrices. Recuperación de 7-10 días. Incluye controles post-operatorios.',
        profesional: 'Dr. Guillermo Contreras',
        especialidad: 'Urólogo',
        valorDesde: 450000,
        valorHasta: null,
        duracion: '45-60 min',
        sesiones: '1 cirugía',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'vasectomia',
        categoria: 'Urología',
        subcategoria: 'Cirugía',
        nombre: 'Vasectomía',
        descripcion: 'Método anticonceptivo permanente masculino mediante la sección de los conductos deferentes. Procedimiento ambulatorio, rápido y seguro bajo anestesia local. No afecta la función sexual ni los niveles hormonales. Recuperación de 2-3 días. Se requiere espermiograma de control a los 3 meses para confirmar efectividad.',
        profesional: 'Dr. Guillermo Contreras',
        especialidad: 'Urólogo',
        valorDesde: 400000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: '1 cirugía',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'frenuloplastia',
        categoria: 'Urología',
        subcategoria: 'Cirugía',
        nombre: 'Frenuloplastía',
        descripcion: 'Corrección quirúrgica del frenillo corto (frenillo breve), condición que puede causar dolor o molestias durante las relaciones sexuales y dificultar la retracción del prepucio. Procedimiento ambulatorio bajo anestesia local. Técnica que alarga el frenillo preservando la sensibilidad. Recuperación rápida de 5-7 días.',
        profesional: 'Dr. Guillermo Contreras',
        especialidad: 'Urólogo',
        valorDesde: 350000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '1 cirugía',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },

    // ==================== GINECOESTÉTICA - STEFANIA KUNCAR ====================
    {
        id: 'rejuvenecimiento-vaginal-laser',
        categoria: 'Ginecoestética',
        subcategoria: 'Láser',
        nombre: 'Rejuvenecimiento Vaginal Láser CO2',
        descripcion: 'Tratamiento con láser CO2 fraccionado para rejuvenecimiento del canal vaginal. Estimula la producción de colágeno, mejora la elasticidad, lubricación natural y tono de los tejidos. Indicado para sequedad vaginal, síndrome genitourinario de la menopausia, laxitud vaginal post-parto e incontinencia urinaria leve. Procedimiento ambulatorio, sin dolor ni tiempo de recuperación.',
        profesional: 'Stefania Kuncar Ferrón',
        especialidad: 'Matrona - Ginecoestética',
        valorDesde: 250000,
        valorHasta: 350000,
        duracion: '30-45 min',
        sesiones: '3 sesiones',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'insercion-diu',
        categoria: 'Ginecoestética',
        subcategoria: 'Anticoncepción',
        nombre: 'Inserción DIU',
        descripcion: 'Colocación de dispositivo intrauterino (DIU) como método anticonceptivo de larga duración. Disponibles opciones hormonales (Mirena, Kyleena) y no hormonales (T de Cobre). Procedimiento rápido realizado en consulta. Efectividad superior al 99%. El DIU es reversible y puede retirarse cuando la paciente lo decida. Incluye ecografía de control.',
        profesional: 'Stefania Kuncar Ferrón',
        especialidad: 'Matrona - Ginecoestética',
        valorDesde: 40000,
        valorHasta: 60000,
        duracion: '20-30 min',
        sesiones: '1 procedimiento',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'insercion-implante',
        categoria: 'Ginecoestética',
        subcategoria: 'Anticoncepción',
        nombre: 'Inserción Implante Anticonceptivo',
        descripcion: 'Colocación de implante subdérmico anticonceptivo (Implanon/Nexplanon) en la cara interna del brazo. Método anticonceptivo de larga duración (3 años), altamente efectivo (99.9%) y reversible. Procedimiento ambulatorio bajo anestesia local. Ideal para mujeres que buscan anticoncepción sin preocupaciones diarias.',
        profesional: 'Stefania Kuncar Ferrón',
        especialidad: 'Matrona - Ginecoestética',
        valorDesde: 50000,
        valorHasta: null,
        duracion: '15-20 min',
        sesiones: '1 procedimiento',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    // ==================== CIRUGÍA MAXILOFACIAL - DR. LUIS PÉREZ ====================
    {
        id: 'bichectomia',
        categoria: 'Cirugía Maxilofacial',
        subcategoria: 'Cirugía',
        nombre: 'Bichectomía',
        descripcion: 'Extracción quirúrgica de las bolsas de Bichat, acumulaciones de grasa en las mejillas que dan un aspecto redondeado al rostro. Se realiza por vía intraoral (sin cicatrices visibles) bajo anestesia local. Afina el rostro, marca los pómulos y define el contorno facial. Resultados definitivos visibles a los 2-3 meses cuando baja la inflamación.',
        profesional: 'Dr. Luis Pérez Lagos',
        especialidad: 'Cirujano Maxilofacial',
        valorDesde: 600000,
        valorHasta: null,
        duracion: '45-60 min',
        sesiones: '1 cirugía',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'blefaroplastia-quirurgica',
        categoria: 'Cirugía Maxilofacial',
        subcategoria: 'Cirugía',
        nombre: 'Blefaroplastía Quirúrgica',
        descripcion: 'Cirugía de rejuvenecimiento de párpados que elimina el exceso de piel, grasa y músculo que causa aspecto cansado, párpados caídos o bolsas. Puede ser superior (párpado de arriba), inferior (bolsas bajo los ojos) o completa. Cicatrices ocultas en pliegues naturales. Resultados duraderos que rejuvenecen significativamente la mirada.',
        profesional: 'Dr. Luis Pérez Lagos',
        especialidad: 'Cirujano Maxilofacial',
        valorDesde: 800000,
        valorHasta: 1500000,
        duracion: '60-90 min',
        sesiones: '1 cirugía',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'otoplastia',
        categoria: 'Cirugía Maxilofacial',
        subcategoria: 'Cirugía',
        nombre: 'Otoplastía',
        descripcion: 'Corrección quirúrgica de orejas prominentes, en asa o con deformidades del cartílago. Se remodela el cartílago auricular para lograr una posición más natural y cercana a la cabeza. Cicatriz oculta detrás de la oreja. Puede realizarse desde los 6-7 años. Mejora significativamente la armonía facial y la autoestima del paciente.',
        profesional: 'Dr. Luis Pérez Lagos',
        especialidad: 'Cirujano Maxilofacial',
        valorDesde: 700000,
        valorHasta: null,
        duracion: '60-90 min',
        sesiones: '1 cirugía',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'lipo-papada',
        categoria: 'Cirugía Maxilofacial',
        subcategoria: 'Cirugía',
        nombre: 'Lipoaspiración de Papada',
        descripcion: 'Eliminación quirúrgica de la grasa submentoniana (papada) mediante lipoaspiración. Procedimiento ambulatorio bajo anestesia local que redefine el contorno del cuello y la línea mandibular. Ideal para personas con acumulación de grasa bajo el mentón resistente a dieta y ejercicio. Resultados definitivos con mínima cicatriz oculta bajo el mentón.',
        profesional: 'Dr. Luis Pérez Lagos',
        especialidad: 'Cirujano Maxilofacial',
        valorDesde: 750000,
        valorHasta: null,
        duracion: '60-90 min',
        sesiones: '1 cirugía',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'lobuloplastia',
        categoria: 'Cirugía Maxilofacial',
        subcategoria: 'Cirugía',
        nombre: 'Lobuloplastia',
        descripcion: 'Corrección quirúrgica de lóbulos de orejas dañados, rasgados o elongados por uso prolongado de aros pesados. Reconstruye el lóbulo para devolverle forma natural y permitir volver a usar aros. Procedimiento ambulatorio bajo anestesia local con resultados definitivos.',
        profesional: 'Dr. Luis Pérez Lagos',
        especialidad: 'Cirujano Maxilofacial',
        valorDesde: 350000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: '1 cirugía',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },

    // ==================== VASCULAR - DRA. FRANCISCA GONZÁLEZ ====================
    {
        id: 'consulta-vascular',
        categoria: 'Vascular',
        subcategoria: 'Consulta',
        nombre: 'Consulta Vascular con Ecografía Doppler',
        descripcion: 'Evaluación vascular completa que incluye anamnesis, examen físico y ecografía Doppler venosa en el mismo momento. Permite diagnosticar várices, insuficiencia venosa, trombosis y otras patologías vasculares. Se determina el mejor tratamiento según hallazgos. Incluye informe ecográfico. Primera consulta indispensable antes de cualquier procedimiento vascular.',
        profesional: 'Dra. Francisca González Saldivia',
        especialidad: 'Cirujana Vascular',
        valorDesde: 50000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: 'Primera consulta',
        requiereEvaluacion: false,
        evaluacionGratuita: false
    },
    {
        id: 'escleroterapia-pequenas',
        categoria: 'Vascular',
        subcategoria: 'Escleroterapia',
        nombre: 'Escleroterapia Várices Pequeñas',
        descripcion: 'Tratamiento de arañitas vasculares y telangiectasias mediante inyección de solución esclerosante. El producto irrita la pared del vaso causando su cierre y reabsorción. Procedimiento ambulatorio, prácticamente indoloro, sin tiempo de recuperación. Requiere uso de medias de compresión post-tratamiento. Resultados visibles en semanas.',
        profesional: 'Dra. Francisca González Saldivia',
        especialidad: 'Cirujana Vascular',
        valorDesde: 80000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '2-4 sesiones',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'escleroterapia-grandes',
        categoria: 'Vascular',
        subcategoria: 'Escleroterapia',
        nombre: 'Escleroterapia Várices Grandes',
        descripcion: 'Tratamiento de várices de mayor calibre mediante escleroterapia con espuma (foam). La espuma esclerosante tiene mayor contacto con la pared venosa, siendo más efectiva para venas grandes. Guiada por ecografía para mayor precisión. Alternativa menos invasiva a la cirugía para muchos casos de insuficiencia venosa.',
        profesional: 'Dra. Francisca González Saldivia',
        especialidad: 'Cirujana Vascular',
        valorDesde: 400000,
        valorHasta: 500000,
        duracion: '45-60 min',
        sesiones: 'Según evaluación',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },

    // ==================== CAPILAR - DRA. JAVIERA ARAYA ====================
    {
        id: 'consulta-capilar',
        categoria: 'Capilar',
        subcategoria: 'Consulta',
        nombre: 'Consulta Médica Capilar',
        descripcion: 'Evaluación integral realizada por un médico especialista orientada a diagnosticar y tratar problemas del cabello y cuero cabelludo, como caída excesiva, adelgazamiento, pérdida de densidad, entradas, caspa, picazón o grasa excesiva. Se revisa historia clínica, antecedentes familiares, hábitos y se examina el cuero cabelludo con dermatoscopia si es necesario.',
        profesional: 'Dra. Javiera Araya Medina',
        especialidad: 'Tricología',
        valorDesde: 40000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: 'Primera consulta',
        requiereEvaluacion: false,
        evaluacionGratuita: false
    },
    {
        id: 'mesoterapia-capilar',
        categoria: 'Capilar',
        subcategoria: 'Mesoterapia',
        nombre: 'Mesoterapia Capilar',
        descripcion: 'Tratamiento médico capilar con microinyecciones superficiales en el cuero cabelludo, introduciendo vitaminas, aminoácidos, minerales y activos específicos para fortalecer el folículo piloso. Ayuda a disminuir la caída, mejorar calidad y grosor del cabello y estimular crecimiento en zonas de adelgazamiento.',
        profesional: 'Dra. Javiera Araya Medina',
        especialidad: 'Tricología',
        valorDesde: 110000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: 'Según plan capilar',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'prp-capilar',
        categoria: 'Capilar',
        subcategoria: 'PRP',
        nombre: 'Plasma Rico en Plaquetas Capilar',
        descripcion: 'Tratamiento que utiliza el propio plasma del paciente, rico en plaquetas y factores de crecimiento, para estimular y fortalecer los folículos pilosos. Se extrae sangre, se centrifuga y se aplica mediante microinyecciones en el cuero cabelludo. Ayuda a disminuir la caída y mejorar la densidad del cabello.',
        profesional: 'Dra. Javiera Araya Medina',
        especialidad: 'Tricología',
        valorDesde: 110000,
        valorHasta: null,
        duracion: '45-60 min',
        sesiones: 'Según plan capilar',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'injerto-capilar',
        categoria: 'Capilar',
        subcategoria: 'Injerto FUE',
        nombre: 'Injerto Capilar FUE',
        descripcion: 'Procedimiento quirúrgico que redistribuye unidades foliculares desde zona donante hacia áreas con pérdida de cabello o baja densidad. Permite recuperar cobertura capilar y mejorar línea frontal y/o coronilla. Requiere evaluación médica detallada previa.',
        profesional: 'Dra. Javiera Araya Medina',
        especialidad: 'Tricología',
        valorDesde: 1500000,
        valorHasta: null,
        duracion: '4-8 horas',
        sesiones: '1 cirugía',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'regenera-capilar',
        categoria: 'Capilar',
        subcategoria: 'Regenera',
        nombre: 'Regenera Activa',
        descripcion: 'Tratamiento capilar avanzado que utiliza células autólogas obtenidas del propio paciente. Se procesan muestras de cuero cabelludo sano para liberar células progenitoras y factores de crecimiento, que se infiltran en zonas con adelgazamiento capilar. Estimula folículos debilitados y mejora calidad del cabello.',
        profesional: 'Dra. Javiera Araya Medina',
        especialidad: 'Tricología',
        valorDesde: 1250000,
        valorHasta: null,
        duracion: '90-120 min',
        sesiones: '1 sesión',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },

    // ==================== CORPORAL - MARÍA JESÚS CONTRERAS ====================
    {
        id: 'consulta-corporal',
        categoria: 'Corporal',
        subcategoria: 'Consulta',
        nombre: 'Consulta Corporal',
        descripcion: 'Evaluación inicial orientada a pacientes que desean mejorar su figura, flacidez, celulitis o grasa localizada. Se evalúa composición corporal, zonas de preocupación, hábitos y objetivos para diseñar un plan personalizado.',
        profesional: 'María Jesús Contreras',
        especialidad: 'Remodelación Corporal',
        valorDesde: 0,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: 'Primera consulta (sin costo)',
        requiereEvaluacion: false,
        evaluacionGratuita: true
    },
    {
        id: 'depilacion-axilas-sesion',
        categoria: 'Corporal',
        subcategoria: 'Depilación Láser',
        nombre: 'Depilación Láser Axilas (1 sesión)',
        descripcion: 'Sesión individual de depilación láser en axilas con Soprano Titanium, tecnología de triple longitud de onda que permite reducción progresiva del vello de forma segura y confortable. Mejora higiene y aspecto de la piel.',
        profesional: 'María Jesús Contreras',
        especialidad: 'Depilación Láser',
        valorDesde: 22000,
        valorHasta: null,
        duracion: '15-20 min',
        sesiones: '1 sesión',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'depilacion-piernas-completas',
        categoria: 'Corporal',
        subcategoria: 'Depilación Láser',
        nombre: 'Depilación Láser Piernas Completas (1 sesión)',
        descripcion: 'Sesión de depilación láser en piernas completas (muslos hasta pies y dedos) con Soprano Titanium. Reduce dependencia de cera o rasuradora, evitando irritación, foliculitis y sombreado.',
        profesional: 'María Jesús Contreras',
        especialidad: 'Depilación Láser',
        valorDesde: 60000,
        valorHasta: null,
        duracion: '60-90 min',
        sesiones: '1 sesión',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'depilacion-cuerpo-completo',
        categoria: 'Corporal',
        subcategoria: 'Depilación Láser',
        nombre: 'Depilación Láser Cuerpo Completo (1 sesión)',
        descripcion: 'Sesión de depilación láser de cuerpo completo con Soprano Titanium, incluyendo piernas, brazos, axilas, zona íntima, abdomen, espalda y glúteos según evaluación.',
        profesional: 'María Jesús Contreras',
        especialidad: 'Depilación Láser',
        valorDesde: 100000,
        valorHasta: 130000,
        duracion: '2-3 horas',
        sesiones: '1 sesión',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'criolipolis-clatuu',
        categoria: 'Corporal',
        subcategoria: 'Criolipólisis',
        nombre: 'Criolipólisis Clatuu Alpha (1 cabezal)',
        descripcion: 'Tratamiento de criolipólisis 360° orientado a reducir grasa localizada en zonas específicas (abdomen, flancos, espalda, brazos, muslos) mediante enfriamiento controlado que actúa selectivamente sobre los adipocitos.',
        profesional: 'María Jesús Contreras',
        especialidad: 'Remodelación Corporal',
        valorDesde: 200000,
        valorHasta: null,
        duracion: '60 min por cabezal',
        sesiones: '1-2 sesiones por zona',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },

    // ==================== GINECOESTÉTICA ====================
    {
        id: 'consulta-ginecologica',
        categoria: 'Ginecoestética',
        subcategoria: 'Consulta',
        nombre: 'Consulta Ginecológica',
        descripcion: 'Consulta médica orientada a salud íntima y ginecológica de la mujer. Aborda controles de rutina, alteraciones menstruales, dolor pélvico, flujo anormal, anticoncepción, cambios postparto o postmenopausia y salud sexual.',
        profesional: 'Dra. María Laura Villarroel',
        especialidad: 'Ginecología',
        valorDesde: 40000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: 'Primera consulta',
        requiereEvaluacion: false,
        evaluacionGratuita: false
    },
    {
        id: 'laser-co2-vaginal',
        categoria: 'Ginecoestética',
        subcategoria: 'Láser CO2',
        nombre: 'Láser CO2 Íntimo Femenino',
        descripcion: 'Tratamiento con láser CO2 fraccionado para rejuvenecimiento vaginal. Mejora sequedad, laxitud, incontinencia leve y síntomas de atrofia vaginal. Estimula producción de colágeno y elastina en mucosa vaginal.',
        profesional: 'Dra. María Laura Villarroel',
        especialidad: 'Ginecología',
        valorDesde: 250000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: '1-3 sesiones',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },
    {
        id: 'consulta-matrona',
        categoria: 'Ginecoestética',
        subcategoria: 'Consulta',
        nombre: 'Consulta Matrona',
        descripcion: 'Consulta orientada a salud ginecológica, íntima y sexual femenina. Aborda control ginecológico básico, molestias íntimas, sequedad vaginal, dolor en relaciones, anticoncepción e inserción de implante.',
        profesional: 'Stefania Kuncar',
        especialidad: 'Matronería',
        valorDesde: 30000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: 'Primera consulta',
        requiereEvaluacion: false,
        evaluacionGratuita: false
    },
    {
        id: 'peeling-intimo',
        categoria: 'Ginecoestética',
        subcategoria: 'Peeling',
        nombre: 'Peeling Íntimo / Blanqueamiento Zonas Íntimas',
        descripcion: 'Tratamiento con peeling químico especializado para aclarar y mejorar la apariencia de zonas íntimas como ingle, zona perianal y vulvar. Promueve renovación celular, mejora textura y uniformiza el tono de la piel. Precio por 1 zona: $130.000 | 2 zonas misma sesión: $150.000.',
        profesional: 'Stefania Kuncar',
        especialidad: 'Matronería',
        valorDesde: 130000,
        valorHasta: 150000,
        duracion: '30-45 min',
        sesiones: '4-6 sesiones (cada 15-21 días)',
        requiereEvaluacion: true,
        evaluacionGratuita: false
    },

    // ==================== UROLOGÍA ====================
    {
        id: 'consulta-urologica',
        categoria: 'Urología',
        subcategoria: 'Consulta',
        nombre: 'Consulta Urológica',
        descripcion: 'Consulta médica especializada orientada a salud íntima y funcional masculina. Evalúa agrandamiento peneano con ácido hialurónico, desempeño sexual, molestias genitales, cambios en forma o tamaño.',
        profesional: 'Dr. Guillermo Contreras',
        especialidad: 'Urología',
        valorDesde: 50000,
        valorHasta: null,
        duracion: '30-45 min',
        sesiones: 'Primera consulta',
        requiereEvaluacion: false,
        evaluacionGratuita: false
    },

    // ==================== AH GLÚTEO ====================
    {
        id: 'ah-gluteo-100ml',
        categoria: 'Corporal',
        subcategoria: 'Relleno Corporal',
        nombre: 'Ácido Hialurónico Glúteo 100ml',
        descripcion: 'Tratamiento corporal mínimamente invasivo con ácido hialurónico de alta densidad para mejorar volumen, proyección y forma de los glúteos. Permite redondear, levantar visualmente y corregir asimetrías.',
        profesional: 'Dra. Elga Viviana Peña',
        especialidad: 'Medicina Estética',
        valorDesde: 600000,
        valorHasta: null,
        duracion: '60-90 min',
        sesiones: '1 sesión (duración 18-24 meses)',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },
    {
        id: 'ah-gluteo-200ml',
        categoria: 'Corporal',
        subcategoria: 'Relleno Corporal',
        nombre: 'Ácido Hialurónico Glúteo 200ml',
        descripcion: 'Tratamiento corporal con ácido hialurónico de alta densidad para volumen y forma de glúteos. Mayor cantidad de producto para resultados más notorios.',
        profesional: 'Dra. Elga Viviana Peña',
        especialidad: 'Medicina Estética',
        valorDesde: 1100000,
        valorHasta: null,
        duracion: '90-120 min',
        sesiones: '1 sesión (duración 18-24 meses)',
        requiereEvaluacion: true,
        evaluacionGratuita: true
    },

    // ==================== NUTRICIÓN ====================
    {
        id: 'consulta-nutricional',
        categoria: 'Nutrición',
        subcategoria: 'Consulta',
        nombre: 'Consulta Nutricional (incluye InBody 970)',
        descripcion: 'Evaluación nutricional integral que incluye anamnesis, medición de composición corporal con InBody 970, análisis de masa muscular, grasa corporal, agua y metabolismo basal. Se entrega plan alimentario personalizado según objetivos.',
        profesional: 'Walter Zaror / Valentina Verdejo',
        especialidad: 'Nutricionistas',
        valorDesde: 40000,
        valorHasta: null,
        duracion: '45-60 min',
        sesiones: 'Primera consulta + controles mensuales',
        requiereEvaluacion: false,
        evaluacionGratuita: false
    },
    {
        id: 'examen-inbody',
        categoria: 'Nutrición',
        subcategoria: 'Exámenes',
        nombre: 'Examen InBody 970 (sin interpretación)',
        descripcion: 'Medición de composición corporal con tecnología InBody 970. Entrega datos de masa muscular, grasa corporal, agua corporal total, metabolismo basal y análisis segmental. Solo examen, sin interpretación profesional.',
        profesional: 'Walter Zaror / Valentina Verdejo',
        especialidad: 'Nutricionistas',
        valorDesde: 15000,
        valorHasta: null,
        duracion: '15 min',
        sesiones: '1 examen',
        requiereEvaluacion: false,
        evaluacionGratuita: false
    },
    {
        id: 'calorimetria-indirecta',
        categoria: 'Nutrición',
        subcategoria: 'Exámenes',
        nombre: 'Calorimetría Indirecta',
        descripcion: 'Medición del gasto energético en reposo mediante calorimetría indirecta. Determina con precisión las calorías que el cuerpo consume en reposo, permitiendo diseñar planes nutricionales más exactos.',
        profesional: 'Walter Zaror / Valentina Verdejo',
        especialidad: 'Nutricionistas',
        valorDesde: 50000,
        valorHasta: null,
        duracion: '30 min',
        sesiones: '1 examen',
        requiereEvaluacion: false,
        evaluacionGratuita: false
    }
];

// Obtener categorías únicas
function getCategoriasTratamientos() {
    const categorias = [...new Set(tratamientosData.map(t => t.categoria))];
    return categorias.sort();
}

// Obtener subcategorías por categoría
function getSubcategoriasTratamientos(categoria) {
    const subcats = [...new Set(tratamientosData.filter(t => t.categoria === categoria).map(t => t.subcategoria))];
    return subcats.sort();
}
